/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the canonical OpenAPI document
         * @description Returns this service's repository-root OpenAPI 3.1 document byte-for-byte.
         */
        get: operations["gateway.openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Always returns 200 once the process is accepting connections. No dependency checks.
         */
        get: operations["gateway.health.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Polls every configured route's upstream(s) on their healthPath (2s timeout each, result cached 15s) and reports per-route healthy/total counts. 200 when every route has at least one healthy upstream, 503 otherwise.
         */
        get: operations["gateway.ready.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service identity and capabilities
         * @description Static identity, capability list and the currently-loaded routes.json revision.
         */
        get: operations["gateway.info.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Prometheus text exposition format: requests by route and status class, request and upstream latency histograms, byte counters, upstream errors, gateway-level rejection counters, circuit breaker state/failures/transitions per route and upstream, process uptime. The endpoint only exists when METRICS_TOKEN is configured — when it is not set, every request (regardless of credentials) gets 404, not 401.
         */
        get: operations["gateway.metrics.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: Record<string, never> | unknown[];
            };
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @description Per-route healthy/total upstream counts, keyed by the route id from routes.json (the key set is deployment-specific). */
            upstreams: {
                [key: string]: string;
            };
        };
        InfoResponse: {
            /** @constant */
            service: "gateway";
            /** @description gateway's own package.json version. */
            version: string;
            /** @constant */
            apiVersion: "v1";
            /**
             * @description Static list of features gateway code supports. Does not reflect whether the rate-limit-policy or geo integrations are actually configured (wired) for this deployment — that depends on routes.json and the RATELIMIT_/GEO_ environment variables.
             * @example [
             *       "jwt-auth",
             *       "rate-limit-policy",
             *       "upstream-health-tracking",
             *       "geo-headers",
             *       "cors",
             *       "trace-propagation"
             *     ]
             */
            capabilities: string[];
            /** @description Always null — gateway has no database and no versioned schema. */
            schemaVersion: null;
            /** @description Always null — gateway is the one service with no @atc-web/service-core dependency. */
            serviceCore: null;
            /** @description File mtime + content hash of the currently-loaded routes.json, changing only on a successful SIGHUP reload; null until the first reload, if the process was never sent one. */
            routesRevision: string | null;
        };
    };
    responses: {
        /** @description Bearer token missing or does not match METRICS_TOKEN. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate": components["headers"]["WWWAuthenticate"];
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                Server: components["headers"]["Server"];
                "Strict-Transport-Security": components["headers"]["StrictTransportSecurity"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "invalid metrics token"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Metrics are disabled because METRICS_TOKEN is not configured. */
        NotFound: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                Server: components["headers"]["Server"];
                "Strict-Transport-Security": components["headers"]["StrictTransportSecurity"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "metrics disabled"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Always set by gateway's response hook unless already set by the handler. */
        XContentTypeOptions: "nosniff";
        /** @description Always set by gateway's response hook unless already set by the handler. */
        ReferrerPolicy: "strict-origin-when-cross-origin";
        /** @description gateway's configured SERVER_NAME (default atc-gateway). */
        Server: string;
        /** @description Present only when the gateway process has TLS configured (HSTS_MAX_AGE > 0). */
        StrictTransportSecurity: string;
        /** @description Present on 401 responses to /metrics. */
        WWWAuthenticate: "Bearer";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "gateway.openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical OpenAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/yaml": string;
                };
            };
        };
    };
    "gateway.health.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    Server: components["headers"]["Server"];
                    "Strict-Transport-Security": components["headers"]["StrictTransportSecurity"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "gateway.ready.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every route has at least one upstream answering its health path. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    Server: components["headers"]["Server"];
                    "Strict-Transport-Security": components["headers"]["StrictTransportSecurity"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description At least one route has zero healthy upstreams. */
            503: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    Server: components["headers"]["Server"];
                    "Strict-Transport-Security": components["headers"]["StrictTransportSecurity"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    "gateway.info.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity and capability information. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    Server: components["headers"]["Server"];
                    "Strict-Transport-Security": components["headers"]["StrictTransportSecurity"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    "gateway.metrics.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics rendered as Prometheus text. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    Server: components["headers"]["Server"];
                    "Strict-Transport-Security": components["headers"]["StrictTransportSecurity"];
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4; charset=utf-8": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
