/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Always returns 200 once the process is accepting connections. No dependency checks.
         */
        get: operations["geo.health.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Runs `db.ping()` and, when MMDB_PATH is configured, checks that the IP database is loaded (`this.ipLookup.available`). The result is cached for 10 seconds (`GeoApi.READY_CACHE_MS`); a successful `POST /v1/database/reload` invalidates the cache so the next `/ready` call re-checks immediately instead of serving a stale verdict from before the reload.
         */
        get: operations["geo.ready.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service identity and capabilities
         * @description Registered outside the `/v1` authentication boundary despite its path: unauthenticated, same as `/health` and `/ready`.
         */
        get: operations["geo.info.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Prometheus text exposition format: IP lookups by result (hit/miss/special), whether the IP database is loaded, its build time, place-collection and place counts, database file size, process uptime. Requires a `read`-role API key (same Bearer auth as `/v1/*`); this route is NOT behind the `/v1` rate limiter (registered in a separate plugin scope that does not install `@fastify/rate-limit`).
         */
        get: operations["geo.metrics.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ip/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up the caller's own IP address
         * @description Looks up `request.ip` (the client address Fastify resolves, honoring TRUST_PROXY). Same lookup logic and response shape as `GET /v1/ip/{ip}`.
         */
        get: operations["geo.ip.lookupSelf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ip/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up an IP address
         * @description Resolves country, region, city, coordinates, time zone and (when ASN_MMDB_PATH is configured) ASN/organization for a public IPv4 or IPv6 address. Special-range addresses (private, loopback, link-local, multicast, reserved, unspecified — `kind` in the response) are classified without consulting the MMDB file and always return `found: false` with every geo field `null`, never a 503, even when no IP database is configured at all. A public address returns 503 DATABASE_UNAVAILABLE only when no city database is configured or the currently loaded one failed; the ASN lookup, when configured, augments the result but never causes a 503 on its own (a missing/failed ASN database just leaves `asn: null`).
         */
        get: operations["geo.ip.lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ip/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Look up multiple IP addresses
         * @description Two-layer size cap: the JSON schema allows up to 1000 items (`maxItems: 1000`) as an outer ceiling — exceeding it fails the whole request with 400 VALIDATION_FAILED before the handler runs. The real operative cap is the `MAX_BATCH` environment variable (default 100, configurable 1-1000); a request between `MAX_BATCH` and 1000 items passes schema validation but is then rejected whole with 413 BATCH_TOO_LARGE by the handler.
         *     **Per-item errors do not fail the batch.** For each IP that passes both caps, any domain error the single-IP lookup would have thrown (`INVALID_IP`, or — most importantly — `DATABASE_UNAVAILABLE`) is caught per item and reported as `{ ip, ok: false, error: { code, message } }` inside an overall HTTP 200. This is a real asymmetry with `GET /v1/ip/{ip}` / `GET /v1/ip/self`: there, `DATABASE_UNAVAILABLE` is a genuine HTTP 503; here, the identical condition never changes the batch's HTTP status — it only ever appears as a per-item `ok: false` entry.
         */
        post: operations["geo.ip.lookupBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current IP database status
         * @description Whether a city/ASN database is loaded, its metadata, when it was loaded, and lookup counters since process start.
         */
        get: operations["geo.database.getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/database/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload the configured IP database file(s) from disk
         * @description Re-reads MMDB_PATH/ASN_MMDB_PATH. Each candidate file is checksum-verified (when MMDB_SHA256/ASN_MMDB_SHA256 or a `<path>.sha256` sidecar is configured), opened, and validated with real lookups for known public IPs (1.1.1.1, 8.8.8.8) — a thrown error at any stage rejects that candidate. Both candidates are fully validated into local variables before either replaces the reader currently serving, so a failure here never disturbs already-loaded databases: on failure the previous readers (if any) keep serving unchanged and this returns 409 DATABASE_RELOAD_FAILED. On success, the response is the same shape as `GET /v1/database`, and the next `GET /ready` re-checks immediately instead of using its 10-second cache.
         */
        post: operations["geo.database.reload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List countries
         * @description Optionally filtered by name/code prefix, continent, EU membership or currency.
         */
        get: operations["geo.countries.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/countries/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a country by code
         * @description Looked up by alpha-2, alpha-3 or numeric code, case-insensitive.
         */
        get: operations["geo.countries.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List currencies
         * @description Every currency used by at least one country in the reference table, sorted by ISO code.
         */
        get: operations["geo.currencies.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/currencies/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a currency by ISO 4217 code
         * @description 404s unless the code is used by at least one country in the reference table (not every ISO 4217 code is accepted).
         */
        get: operations["geo.currencies.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/timezones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List time zones
         * @description Every IANA zone name Node's ICU knows plus every zone in the reference table (their union), optionally filtered.
         */
        get: operations["geo.timezones.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/timezones/{tzPath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a time zone by IANA name
         * @description **Wildcard route caveat**: the real Fastify route is `GET /v1/timezones/*`, a wildcard that captures everything after `/v1/timezones/` as one string — including embedded `/` characters (e.g. `Europe/Istanbul`, `America/Argentina/Buenos_Aires`). Standard OpenAPI `{param}` path templating cannot represent an embedded-slash capture in one segment; the `{tzPath}` placeholder here is a documentation convention for "the rest of the path", not a single path segment. A client must URL-encode each `/` only if its HTTP library would otherwise treat it as a path separator before it reaches this route — Fastify itself matches the raw path against the wildcard, embedded slashes included, unencoded. Both the current IANA name and recognized aliases resolvable by the runtime's ICU (e.g. `Asia/Calcutta`) are accepted; unresolvable names return 404 TIMEZONE_NOT_FOUND.
         */
        get: operations["geo.timezones.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Normalize a phone number to E.164
         * @description National numbering plans are not modelled: validity only checks that the resolved calling code is known and the digit count is 8-15 (E.164 length rule), not that the subscriber number actually exists. When `number` has no `+`/`00` international prefix, `country` is required to resolve it as a national number; if `country` is given but not a known country code, this returns 404 COUNTRY_NOT_FOUND (not a 400) — the same code `GET /v1/countries/{code}` uses. An unresolvable international calling code, or a missing `country` for a national-format number, is not an error: it returns 200 with `valid: false` and a `reason`.
         */
        get: operations["geo.phone.normalize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phone/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Normalize multiple phone numbers
         * @description Same two-layer size cap as `POST /v1/ip/batch`: JSON schema allows up to 1000 items (`maxItems: 1000`) as an outer ceiling (exceeding it is 400 VALIDATION_FAILED before the handler runs); the real operative cap is `MAX_BATCH` (default 100) — between `MAX_BATCH` and 1000 items is rejected whole with 413 BATCH_TOO_LARGE.
         *     Per-item errors do not fail the batch: any domain error a single normalize call would throw for one number — `INVALID_PHONE`, or `COUNTRY_NOT_FOUND` when the shared `country` is not a known code — is caught per item and reported as `{ number, ok: false, error: { code, message } }` inside an overall HTTP 200, exactly like `POST /v1/ip/batch`. Phone normalization has no database dependency, so unlike the IP batch route there is no `DATABASE_UNAVAILABLE` case here.
         */
        post: operations["geo.phone.normalizeBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/distance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Great-circle distance and bearing between two points
         * @description Haversine distance on a WGS-84 sphere (R = 6371.0088 km) between any two valid coordinates. Unlike `GET /v1/collections/{name}/nearby`, there is no radius cap here — `MAX_RADIUS_KM` does not apply to this route at all; any two points that individually pass coordinate validation (lat in [-90,90], lng in [-180,180]) are accepted, however far apart.
         */
        get: operations["geo.distance.compute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List place collections */
        get: operations["geo.collections.list"];
        put?: never;
        /** Create a place collection */
        post: operations["geo.collections.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a place collection */
        get: operations["geo.collections.get"];
        put?: never;
        post?: never;
        /** Delete a place collection and all its places */
        delete: operations["geo.collections.delete"];
        options?: never;
        head?: never;
        /** Update a place collection's description */
        patch: operations["geo.collections.patch"];
        trace?: never;
    };
    "/v1/collections/{name}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove every place from a collection
         * @description The collection itself is kept; only its places are removed.
         */
        post: operations["geo.collections.clear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{name}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List places in a collection */
        get: operations["geo.places.list"];
        /**
         * Insert or replace places in a collection, all or nothing
         * @description Atomic: either every place in the request is applied, or (on a duplicate `id` within the request, an empty name, invalid coordinates, or the collection's MAX_POINTS cap being exceeded) none of it is, and the whole call fails with 400 INVALID_PLACE or 413 BATCH_TOO_LARGE. The MAX_POINTS cap (default 5000, env-configurable) limits the total number of places in one collection after the call, and is distinct from this route's own request-size ceiling (`maxItems: 100000` places per call).
         */
        put: operations["geo.places.upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{name}/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a place by id */
        get: operations["geo.places.get"];
        put?: never;
        post?: never;
        /** Delete a place */
        delete: operations["geo.places.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{name}/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Places near a point, nearest first
         * @description `radius` (km) defaults to `min(50, MAX_RADIUS_KM)` and must be between 0 (exclusive) and `MAX_RADIUS_KM` (env-configurable, default 500); out of range fails with 400 INVALID_COORDINATES — the same code used for an invalid `lat`/`lng` (`GeoError.STATUS.INVALID_COORDINATES` is genuinely overloaded across both triggers). Extra query parameters of the form `filter.<key>=<value>` (not individually listed below — the key name is caller-defined) restrict results to places whose `attrs[<key>]` string-equals `<value>`; every other query key must be one of the ones listed.
         */
        get: operations["geo.places.nearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate service statistics */
        get: operations["geo.stats.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: Record<string, never> | unknown[];
            };
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @description Present only when status is "unavailable". */
            error?: string;
        };
        InfoResponse: {
            /** @constant */
            service: "geo";
            /** @description geo's own package.json version. */
            version: string;
            /** @constant */
            apiVersion: "v1";
            /**
             * @example [
             *       "ip-lookup",
             *       "phone-normalize",
             *       "distance",
             *       "place-search",
             *       "manual-reload"
             *     ]
             */
            capabilities: string[];
            /** @description geo's SQLite schema version (PRAGMA user_version). */
            schemaVersion: number;
            /** @description Version of the @atc-web/service-core package actually running. */
            serviceCore: string;
        };
        Point: {
            lat: number;
            lng: number;
        };
        IpCountry: {
            /** @description ISO 3166-1 alpha-2. */
            code: string;
            name: string;
            eu: boolean;
            /**
             * @example [
             *       "+90"
             *     ]
             */
            callingCodes: string[];
            currency: string | null;
        };
        IpLookupResult: {
            ip: string;
            /** @enum {integer} */
            version: 4 | 6;
            /** @enum {string} */
            kind: "public" | "private" | "loopback" | "link-local" | "multicast" | "reserved" | "unspecified";
            /** @description False for a special-range address, or a public address not covered by the loaded database. */
            found: boolean;
            /** @description CIDR of the matched record */
            network: string | null;
            country: components["schemas"]["IpCountry"] | null;
            registeredCountry: components["schemas"]["IpCountry"] | null;
            continent: {
                code: string | null;
                name: string | null;
            } | null;
            region: {
                code: string | null;
                name: string | null;
            } | null;
            city: {
                name: string;
            } | null;
            postal: string | null;
            location: {
                lat: number;
                lng: number;
                accuracyKm: number | null;
            } | null;
            /** @description IANA zone name. */
            timezone: string | null;
            /** @description Present only when ASN_MMDB_PATH is configured and covers this address. */
            asn: {
                number: number | null;
                organization: string | null;
                /** @description CIDR of the matched ASN record. */
                network: string;
            } | null;
            /** @description database_type of the loaded city database */
            source: string | null;
        };
        IpBatchRequest: {
            ips: string[];
            lang?: string;
        };
        IpBatchItem: {
            ip: string;
            ok: boolean;
            /** @description Present when ok is true. */
            result?: components["schemas"]["IpLookupResult"];
            /** @description Present when ok is false. */
            error?: {
                /** @enum {string} */
                code: "INVALID_IP" | "DATABASE_UNAVAILABLE";
                message: string;
            };
        };
        IpBatchResponse: {
            items: components["schemas"]["IpBatchItem"][];
        };
        MmdbInfo: {
            /** @example GeoLite2-City */
            type: string;
            buildEpoch: number;
            /** Format: date-time */
            builtAt: string;
            /** @enum {integer} */
            ipVersion: 4 | 6;
            nodeCount: number;
            /** @enum {integer} */
            recordSize: 24 | 28 | 32;
            languages: string[];
            /** @description Language-tag-keyed description strings from the MMDB metadata block. */
            description: Record<string, never>;
            path: string | null;
            sizeBytes: number;
            /** Format: date-time */
            modifiedAt: string | null;
        };
        DatabaseInfo: {
            /** @description Whether MMDB_PATH is set. */
            configured: boolean;
            loaded: boolean;
            /** @description Message from the last failed load/reload attempt. */
            error: string | null;
            /** Format: date-time */
            loadedAt: string | null;
            city: components["schemas"]["MmdbInfo"] | null;
            asn: components["schemas"]["MmdbInfo"] | null;
            lookups: {
                hit: number;
                miss: number;
                special: number;
            };
        };
        CountryView: {
            /** @description ISO 3166-1 alpha-2. */
            code: string;
            alpha3: string;
            numeric: string;
            /** @description Localized via lang. */
            name: string;
            continent: {
                /** @enum {string} */
                code: "AF" | "AN" | "AS" | "EU" | "NA" | "OC" | "SA";
                name: string;
            };
            eu: boolean;
            /**
             * @example [
             *       "+90"
             *     ]
             */
            callingCodes: string[];
            currency: {
                code: string;
                name: string;
            } | null;
            timezones: string[];
            /** @description Regional-indicator flag emoji. */
            flag: string;
        };
        CurrencyView: {
            code: string;
            /** @description Localized via lang. */
            name: string;
            symbol: string;
            decimals: number;
            /** @description Alpha-2 codes of countries using this currency. */
            countries: string[];
        };
        TimezoneView: {
            /** @description Canonical IANA name. */
            name: string;
            /** @example +03:00 */
            offset: string;
            offsetMinutes: number;
            /** @example +03 */
            abbreviation: string;
            /** @description Localized via lang. */
            longName: string;
            /** @description Currently observing DST. */
            dst: boolean;
            /** @description Observes DST at some point in the current year */
            observesDst: boolean;
            /** @description Local wall-clock time at the evaluated instant, "YYYY-MM-DDTHH:mm:ss" (no offset/Z suffix). */
            localTime: string;
            /** @description Alpha-2 codes of countries using this zone. */
            countries: string[];
        };
        PhoneResult: {
            input: string;
            e164: string | null;
            valid: boolean;
            reason: string | null;
            /** @description Best-guess alpha-2; first of countries. */
            country: string | null;
            /** @description Every country sharing the resolved calling code, best match first. */
            countries: string[];
            /** @example +90 */
            callingCode: string | null;
            national: string;
        };
        PhoneBatchRequest: {
            numbers: string[];
            country?: string;
        };
        PhoneBatchItem: {
            number: string;
            ok: boolean;
            /** @description Present when ok is true. */
            result?: components["schemas"]["PhoneResult"];
            /** @description Present when ok is false. */
            error?: {
                /** @enum {string} */
                code: "INVALID_PHONE" | "COUNTRY_NOT_FOUND";
                message: string;
            };
        };
        PhoneBatchResponse: {
            items: components["schemas"]["PhoneBatchItem"][];
        };
        CollectionView: {
            name: string;
            description: string;
            places: number;
            /** @description API key id that created the collection. */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PlaceInput: {
            id: string;
            name: string;
            lat: number;
            lng: number;
            /** @description Arbitrary caller-defined attributes; string values are matched by nearby's filter.<key> query parameters. */
            attrs?: Record<string, never>;
        };
        PlaceView: {
            id: string;
            name: string;
            lat: number;
            lng: number;
            attrs: Record<string, never>;
            /** Format: date-time */
            updatedAt: string;
        };
        NearbyPlace: components["schemas"]["PlaceView"] & {
            /** @description Rounded to 3 decimals. */
            distanceKm: number;
            /** @description Initial bearing in degrees from north */
            bearing: number;
        };
    };
    responses: {
        /** @description The lookup result. `found: false` for a special-range address or a public address not covered by the database. */
        IpLookupOk: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["IpLookupResult"];
            };
        };
        /** @description Current IP database status. */
        DatabaseInfoOk: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DatabaseInfo"];
            };
        };
        /** @description The normalization result. `valid: false` for an unresolvable calling code or a missing country on a national-format number — not an error. */
        PhoneNormalizeOk: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PhoneResult"];
            };
        };
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate": components["headers"]["WWWAuthenticate"];
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "missing or invalid API key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The API key does not have the role this route requires. */
        Forbidden: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "this API key has no write access"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Per-API-key rate limit exceeded (RATE_LIMIT_MAX per minute, default 3000). Applies to every `/v1/*` route; NOT enforced on `/metrics`. */
        RateLimited: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "rate limit exceeded, retry in 42 seconds"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request failed JSON Schema validation (missing/extra/malformed field). */
        ValidationFailed: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_FAILED",
                 *         "message": "body/ips must NOT have more than 1000 items",
                 *         "details": [
                 *           {
                 *             "path": "/ips",
                 *             "message": "must NOT have more than 1000 items",
                 *             "params": {
                 *               "limit": 1000
                 *             }
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The value is not a parseable IPv4 or IPv6 address. */
        InvalidIp: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INVALID_IP",
                 *         "message": "\"not-an-ip\" is not an IP address"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `lat`/`lng` out of range or unparseable, OR (on `/nearby` only) `radius` out of range — both use the same INVALID_COORDINATES code. */
        InvalidCoordinates: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INVALID_COORDINATES",
                 *         "message": "lat must be between -90 and 90"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The number is empty, or contains characters other than digits/spaces/parentheses/dots/dashes. */
        InvalidPhone: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INVALID_PHONE",
                 *         "message": "number is empty"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description More than MAX_BATCH items in this batch call (see the route description for the two-layer cap). */
        BatchTooLarge: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "BATCH_TOO_LARGE",
                 *         "message": "at most 100 items per batch"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No country matches this code. */
        CountryNotFound: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COUNTRY_NOT_FOUND",
                 *         "message": "country \"zz\" not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The code is not used by any country in the reference table. */
        CurrencyNotFound: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "CURRENCY_NOT_FOUND",
                 *         "message": "currency \"zzz\" is not used by any country"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The name does not resolve to a known IANA time zone. */
        TimezoneNotFound: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "TIMEZONE_NOT_FOUND",
                 *         "message": "time zone \"Not/AZone\" not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No collection with this name exists. */
        CollectionNotFound: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COLLECTION_NOT_FOUND",
                 *         "message": "collection \"stores\" not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description A collection with this name already exists. */
        CollectionExists: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COLLECTION_EXISTS",
                 *         "message": "collection \"stores\" already exists"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No IP city database is configured, or the configured one failed to load. Only reachable for a public address; special-range addresses never trigger this. */
        DatabaseUnavailable: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "DATABASE_UNAVAILABLE",
                 *         "message": "no IP database configured (MMDB_PATH)"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The reload attempt failed checksum verification, opening or validation; the previously loaded database (if any) is untouched and still serving. */
        DatabaseReloadFailed: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "DATABASE_RELOAD_FAILED",
                 *         "message": "IP database failed to reload: city database checksum mismatch for ./data/city.mmdb: expected ..., got ..."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
        Lang: string;
        CollectionName: string;
        PlaceId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Set on every response by geo's onSend hook. */
        XContentTypeOptions: "nosniff";
        /** @description Set on every response by geo's onSend hook. */
        CacheControl: "no-store";
        /** @description Present on 401 responses. */
        WWWAuthenticate: "Bearer";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "geo.health.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "geo.ready.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The database check (if applicable) passed. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description `db.ping()` failed, or MMDB_PATH is configured but no IP database is currently loaded (never loaded, or the last load/reload attempt failed checksum, parsing or validation). */
            503: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    "geo.info.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity and capability information. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    "geo.metrics.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics rendered as Prometheus text. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4; charset=utf-8": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "geo.ip.lookupSelf": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["IpLookupOk"];
            400: components["responses"]["InvalidIp"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["DatabaseUnavailable"];
        };
    };
    "geo.ip.lookup": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                /** @example 1.1.1.1 */
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["IpLookupOk"];
            400: components["responses"]["InvalidIp"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["DatabaseUnavailable"];
        };
    };
    "geo.ip.lookupBatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IpBatchRequest"];
            };
        };
        responses: {
            /** @description One result per input IP, in the same order, each independently ok or failed (see description above — a per-item failure never changes this 200). */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpBatchResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["BatchTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.database.getInfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DatabaseInfoOk"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.database.reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DatabaseInfoOk"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["DatabaseReloadFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.countries.list": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
                /** @description Case/accent-folded prefix match against the localized name, alpha-2 or alpha-3 code. */
                q?: string;
                continent?: "AF" | "AN" | "AS" | "EU" | "NA" | "OC" | "SA" | "af" | "an" | "as" | "eu" | "na" | "oc" | "sa";
                eu?: "true" | "false";
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Countries matching the filter, sorted by localized name. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CountryView"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.countries.get": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                /** @example TR */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matched country. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        country: components["schemas"]["CountryView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CountryNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.currencies.list": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All currencies. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CurrencyView"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.currencies.get": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                /** @example TRY */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matched currency. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        currency: components["schemas"]["CurrencyView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CurrencyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.timezones.list": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
                /** @description Restrict to the zones of one country (alpha-2/alpha-3/numeric). 404s (COUNTRY_NOT_FOUND) if the country is unknown. */
                country?: string;
                /** @description Case-insensitive substring match against the zone name. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching time zones, evaluated at the current instant. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TimezoneView"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CountryNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.timezones.get": {
        parameters: {
            query?: {
                /** @description BCP 47 language tag for localized names. Invalid or unrecognized tags never error — they silently fall back to DEFAULT_LANG (env-configurable, default "en"). */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                /**
                 * @description The full IANA time zone name, embedded slashes included (see the wildcard caveat above).
                 * @example Europe/Istanbul
                 */
                tzPath: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matched time zone. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        timezone: components["schemas"]["TimezoneView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["TimezoneNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.phone.normalize": {
        parameters: {
            query: {
                /** @example +90 532 000 00 00 */
                number: string;
                /**
                 * @description Default country for a number given without an international prefix.
                 * @example TR
                 */
                country?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PhoneNormalizeOk"];
            400: components["responses"]["InvalidPhone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CountryNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.phone.normalizeBatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneBatchRequest"];
            };
        };
        responses: {
            /** @description One result per input number, in the same order, each independently ok or failed. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneBatchResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["BatchTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.distance.compute": {
        parameters: {
            query: {
                /** @example 41.0082,28.9784 */
                from: string;
                /** @example 40.7128,-74.0060 */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distance and initial bearing from `from` to `to`. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        from: components["schemas"]["Point"];
                        to: components["schemas"]["Point"];
                        /** @description Great-circle distance */
                        km: number;
                        /** @description Distance in meters */
                        m: number;
                        /** @description Distance in miles */
                        mi: number;
                        /** @description Initial bearing in degrees from north */
                        bearing: number;
                    };
                };
            };
            400: components["responses"]["InvalidCoordinates"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.collections.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every collection, with its current place count. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CollectionView"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.collections.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description The created collection (0 places). */
            201: {
                headers: {
                    /** @description `/v1/collections/{name}` */
                    Location?: string;
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        collection: components["schemas"]["CollectionView"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["CollectionExists"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.collections.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matched collection. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        collection: components["schemas"]["CollectionView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CollectionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.collections.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CollectionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.collections.patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    description?: string;
                };
            };
        };
        responses: {
            /** @description The updated collection. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        collection: components["schemas"]["CollectionView"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CollectionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.collections.clear": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of places removed. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        removed: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CollectionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.places.list": {
        parameters: {
            query?: {
                /** @description Default 50. */
                limit?: string;
                /** @description Default 0. */
                offset?: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of places. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PlaceView"][];
                        /** @description Total places in the collection */
                        total: number;
                        limit: number;
                        offset: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CollectionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.places.upsert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    places: components["schemas"]["PlaceInput"][];
                };
            };
        };
        responses: {
            /** @description Counts for this call. `total` is the collection's place count after the call (places existing before the call, plus newly created ones — an updated place does not change the count). */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created: number;
                        updated: number;
                        total: number;
                    };
                };
            };
            /** @description A schema validation failure, or an invalid place (duplicate id, empty name, or out-of-range coordinates) — see the shared ErrorEnvelope; `code` is `VALIDATION_FAILED` or `INVALID_PLACE`. */
            400: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CollectionNotFound"];
            413: components["responses"]["BatchTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.places.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
                id: components["parameters"]["PlaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matched place. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        place: components["schemas"]["PlaceView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The collection does not exist, or it exists but has no place with this id. */
            404: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.places.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
                id: components["parameters"]["PlaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The collection does not exist, or it exists but has no place with this id. */
            404: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.places.nearby": {
        parameters: {
            query: {
                lat: string;
                lng: string;
                /** @description Kilometers. Default min(50, MAX_RADIUS_KM). */
                radius?: string;
                /** @description Default 10, clamped to [1,100]. */
                limit?: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Places within `radiusKm` of the point, nearest first. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        from: components["schemas"]["Point"];
                        radiusKm: number;
                        /** @description Matches found within the radius */
                        total: number;
                        items: components["schemas"]["NearbyPlace"][];
                    };
                };
            };
            400: components["responses"]["InvalidCoordinates"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CollectionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "geo.stats.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database status plus collection/place totals. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        database: components["schemas"]["DatabaseInfo"];
                        /** @description Size of the bundled reference table (fixed */
                        countries: number;
                        collections: number;
                        /** @description Places across every collection. */
                        places: number;
                        /** @description Size of the SQLite store backing collections/places. */
                        dbBytes: number;
                        /** @description One entry per collection. */
                        items: {
                            name: string;
                            places: number;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
