/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the canonical OpenAPI document
         * @description Returns this service's repository-root OpenAPI 3.1 document byte-for-byte.
         */
        get: operations["notify.openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always returns 200 with no dependency check. Does not require authentication and is never rate limited.
         */
        get: operations["notify.health.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Runs a dependency check (database ping, then `verify()` on every configured delivery channel) and caches the result for `NotifyApi.READY_CACHE_MS` (30 seconds). Also reports whether a worker process is currently alive, inferred from a recent `worker_heartbeat` row (this API process never runs an in-process Worker itself). Does not require authentication and is never rate limited.
         */
        get: operations["notify.ready.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service identity and capabilities
         * @description Public, unauthenticated, uncached. `capabilities` is computed live from the channels actually wired into this instance: it drops `"webhook"` when `NOTIFY_WEBHOOK_CHANNEL=false` (Stage 7), so it always reflects real, currently-enabled behavior rather than a static list.
         */
        get: operations["notify.info.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Prometheus text exposition format. Requires the same Bearer API key as `/v1/*`, but is registered outside the `/v1` rate-limit plugin scope and is therefore never rate limited (a deliberate, platform-wide convention so a fixed-schedule scraper is never throttled).
         */
        get: operations["notify.metrics.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List this API key's messages
         * @description Cursor-paginated, newest first (`created_at DESC, id DESC`). Only returns messages created under the caller's own API key. No Fastify `response:` schema is declared for this route at the source level; the shape below is derived directly from the handler's real return value.
         */
        get: operations["notify.messages.list"];
        put?: never;
        /**
         * Queue a message for delivery
         * @description Inserts the message and returns immediately (`202` for a newly-created message, `200` when the request replays an existing `idempotencyKey`); actual delivery happens later, out of band, via the worker process. Body is polymorphic on `channel` (`email` or `webhook`); an `email` body's `data` is additionally validated, at request time, against the named template's own JSON Schema (`GET /v1/templates` lists the templates this instance ships with, each with its schema).
         *     **Idempotency**: `idempotencyKey`, when given, scopes one logical send per API key. Reusing a key with the identical channel and payload replays the original row (`200`); reusing it with a different channel or payload is a conflict (`409 IDEMPOTENCY_CONFLICT`) — the key is not a slot to overwrite.
         *     **State machine**: `queued -> processing -> sent | failed`. A `failed` message is retryable exactly once per call via `POST /v1/messages/{id}/retry` (full attempt-budget reset, not automatic); there is no cancel/abort endpoint. Automatic retries use exponential backoff with jitter (`BACKOFF_BASE_MS`, default 5000ms; `BACKOFF_CAP_MS`, default 3600000ms) up to `MAX_ATTEMPTS` attempts (default 8) before a message is settled as `failed`.
         */
        post: operations["notify.messages.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one message
         * @description Scoped to the caller's own API key — a message id belonging to a different key is reported as `404`, identically to an unknown id. No Fastify `response:` schema is declared for `200` at the source level; the shape below is derived directly from `MessageView.from()`.
         */
        get: operations["notify.messages.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually re-queue a failed message
         * @description Only a message in `failed` status can be retried. On success, resets `attempts` to 0 and `status` to `queued` for an immediate delivery attempt (a full attempt-budget reset against the same `maxAttempts` the message was created with) — this is not itself counted as a delivery attempt. Scoped to the caller's own API key.
         */
        post: operations["notify.messages.retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List email templates
         * @description The email templates bundled with this service (`TemplateRegistry.withDefaults()`): fixed, code-shipped templates, not operator-configurable. As of this version there are exactly three — `email-verification`, `password-reset`, `generic` — each with its own JSON Schema for the `data` field an email-channel `POST /v1/messages` body must satisfy.
         */
        get: operations["notify.templates.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable error code, e.g. `VALIDATION_FAILED`, `NOT_FOUND`, `IDEMPOTENCY_CONFLICT`. */
                code: string;
                message: string;
                /** @description Present for `VALIDATION_FAILED`; one entry per failed constraint. */
                details?: ({
                    /** @description JSON pointer into the request (e.g. `/to/0`, `/data/appName`). */
                    path?: string;
                    message?: string;
                    params?: {
                        [key: string]: unknown;
                    };
                } & {
                    [key: string]: unknown;
                })[];
            };
        };
        HealthOk: {
            /** @constant */
            status: "ok";
        };
        ReadyOk: {
            /** @constant */
            status: "ok";
            /**
             * @description `running` if a `worker_heartbeat` row was written within `HEARTBEAT_MS x 4` of now, else `stopped`. This API process has no in-process worker to ask directly.
             * @enum {string}
             */
            worker: "running" | "stopped";
        };
        ReadyUnavailable: {
            /** @constant */
            status: "unavailable";
            error: string;
        };
        InfoResponse: {
            /** @constant */
            service: "notify";
            /** @description This service's own package.json semver. */
            version: string;
            /** @constant */
            apiVersion: "v1";
            /**
             * @description Real, currently-enabled behaviors only. Always includes `templates` and `idempotency`; includes `email` when the email channel is configured, and `webhook` unless `NOTIFY_WEBHOOK_CHANNEL=false`.
             * @example [
             *       "email",
             *       "webhook",
             *       "templates",
             *       "idempotency"
             *     ]
             */
            capabilities: string[];
            /** @description Current SQLite `PRAGMA user_version` for this instance's database. */
            schemaVersion: number;
            /** @description Version of the `@atc-web/service-core` package this instance is running. */
            serviceCore: string;
        };
        /** @enum {string} */
        MessageStatus: "queued" | "processing" | "sent" | "failed";
        /** @description Public view of a queued message. Template `data` is never exposed (it may hold PII). */
        Message: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            channel: "email" | "webhook";
            status: components["schemas"]["MessageStatus"];
            /** @description Template name. Populated for `channel: email` only; `null` for `webhook`. */
            template: string | null;
            /** @description Event name. Populated for `channel: webhook` only; `null` for `email`. */
            event: string | null;
            /** @description Recipient addresses. Populated for `channel: email` only; `null` for `webhook`. */
            to: string[] | null;
            /** @description Target URL. Populated for `channel: webhook` only; `null` for `email`. */
            url: string | null;
            /** @description Delivery attempts made so far. */
            attempts: number;
            /** @description Attempt budget this message was created with (`MAX_ATTEMPTS`, default 8). */
            maxAttempts: number;
            /**
             * Format: date-time
             * @description Next scheduled delivery attempt. Only set while `status` is `queued`; `null` otherwise.
             */
            nextAttemptAt: string | null;
            /** @description Error from the most recent failed attempt, truncated to 2000 characters. */
            lastError: string | null;
            /** @description Provider reference from the successful attempt (SMTP message id, or `http <status>` for a webhook), once `status` is `sent`. */
            providerId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            sentAt: string | null;
        };
        MessageList: {
            items: components["schemas"]["Message"][];
            /** @description Opaque cursor for the next page, or `null` when this is the last page. */
            nextCursor: string | null;
        };
        MessageCreateEmail: {
            /** @constant */
            channel: "email";
            /**
             * @description Must name a template returned by `GET /v1/templates`. This enum reflects the exact fixed set of templates `TemplateRegistry.withDefaults()` ships as of this version; a future template addition would extend it.
             * @enum {string}
             */
            template: "email-verification" | "password-reset" | "generic";
            to: components["schemas"]["EmailList"];
            cc?: components["schemas"]["EmailList"];
            bcc?: components["schemas"]["EmailList"];
            /** Format: email */
            replyTo?: string;
            /** @description Validated server-side against the named template's own JSON Schema (see the `if`/`then` branches below, one per template, and `GET /v1/templates` for the same schemas at runtime). `locale` defaults to `tr` when omitted on every template. */
            data: Record<string, never>;
            idempotencyKey?: components["schemas"]["IdempotencyKey"];
        } & (unknown & unknown & unknown & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            channel: "email";
        });
        MessageCreateWebhook: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            channel: "webhook";
            /**
             * Format: uri
             * @description HTTP(S) target. Resolved through an SSRF guard at delivery time; redirects are not followed.
             */
            url: string;
            event: string;
            /** @description Free-form JSON, opaque to notify — sent verbatim as the delivered payload's `data` field. No further schema is enforced (unlike the `email` channel's per-template `data`). */
            data: Record<string, never>;
            /** @description Extra outbound request headers. Only `X-*` and `Authorization` names are allowed; values must be single-line printable ASCII (no CR/LF). */
            headers?: {
                [key: string]: string;
            };
            idempotencyKey?: components["schemas"]["IdempotencyKey"];
        };
        EmailList: string[];
        /** @description Scopes one logical send per API key. Reusing it with an identical channel+payload replays the original message; reusing it with a different one is a `409 IDEMPOTENCY_CONFLICT`. */
        IdempotencyKey: string;
        TemplateDescriptor: {
            name: string;
            description: string;
            /** @description JSON Schema for this template's `data` field, as used to validate `POST /v1/messages`. */
            schema: {
                [key: string]: unknown;
            };
        };
        TemplateList: {
            items: components["schemas"]["TemplateDescriptor"][];
        };
    };
    responses: {
        /** @description `UNAUTHORIZED` — missing or invalid Bearer API key. */
        Unauthorized: {
            headers: {
                "www-authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `NOT_FOUND` — no message with this id exists under the caller's API key. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `RATE_LIMITED` — this API key exceeded `RATE_LIMIT_MAX` requests in the current one-minute window. */
        RateLimited: {
            headers: {
                "retry-after": components["headers"]["RetryAfter"];
                "x-ratelimit-limit": components["headers"]["RateLimitLimit"];
                "x-ratelimit-remaining": components["headers"]["RateLimitRemaining"];
                "x-ratelimit-reset": components["headers"]["RateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `INTERNAL_ERROR` — an unclassified server-side failure. The message is never a leaked internal detail. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        MessageId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Path of the created/replayed message, for polling (`GET /v1/messages/{id}`). */
        Location: string;
        /** @description Requests allowed per rolling one-minute window for this API key (`RATE_LIMIT_MAX`, default 600). */
        RateLimitLimit: number;
        /** @description Requests remaining in the current window for this API key. */
        RateLimitRemaining: number;
        /** @description Seconds until the current window resets. */
        RateLimitReset: number;
        /** @description Seconds to wait before retrying, present only once the per-key rate limit has been exceeded. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "notify.openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical OpenAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/yaml": string;
                };
            };
        };
    };
    "notify.health.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOk"];
                };
            };
        };
    };
    "notify.ready.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOk"];
                };
            };
            /** @description A dependency check failed (database unreachable, or a channel's `verify()` threw). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyUnavailable"];
                };
            };
        };
    };
    "notify.info.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    "notify.metrics.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition (`notify_messages`, `notify_oldest_queued_age_seconds`, `notify_worker_up`, `notify_process_uptime_seconds`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    "notify.messages.list": {
        parameters: {
            query?: {
                status?: components["schemas"]["MessageStatus"];
                /** @description 1-100. Defaults to 20 when omitted. */
                limit?: string;
                /** @description Opaque pagination cursor from a previous response's `nextCursor`. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages. */
            200: {
                headers: {
                    "x-ratelimit-limit": components["headers"]["RateLimitLimit"];
                    "x-ratelimit-remaining": components["headers"]["RateLimitRemaining"];
                    "x-ratelimit-reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            /** @description `VALIDATION_FAILED` (malformed `status`/`limit`/`cursor` value per the query schema) or `INVALID_CURSOR` (a `cursor` that passed schema validation but does not decode to a real pagination position). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    "notify.messages.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreateEmail"] | components["schemas"]["MessageCreateWebhook"];
            };
        };
        responses: {
            /** @description Idempotent replay — an existing message with the same `idempotencyKey`, channel and payload was returned unchanged. */
            200: {
                headers: {
                    location: components["headers"]["Location"];
                    "x-ratelimit-limit": components["headers"]["RateLimitLimit"];
                    "x-ratelimit-remaining": components["headers"]["RateLimitRemaining"];
                    "x-ratelimit-reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description New message accepted and queued for delivery. */
            202: {
                headers: {
                    location: components["headers"]["Location"];
                    "x-ratelimit-limit": components["headers"]["RateLimitLimit"];
                    "x-ratelimit-remaining": components["headers"]["RateLimitRemaining"];
                    "x-ratelimit-reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description `VALIDATION_FAILED` — the body failed JSON Schema validation (unknown/missing field, wrong `channel` discriminator, malformed email/URL/event name, disallowed webhook header name, etc.), or an `email` message's `data` failed the named template's own schema (`details[].path` is prefixed `/data`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `WEBHOOK_CHANNEL_DISABLED` — `channel: "webhook"` was submitted while this instance runs with `NOTIFY_WEBHOOK_CHANNEL=false`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description `IDEMPOTENCY_CONFLICT` — `idempotencyKey` was already used by this API key with a different channel or payload. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request body exceeded `BODY_LIMIT` (default 65536 bytes). Raised by Fastify's own content-type parser before route validation runs (`FST_ERR_CTP_BODY_TOO_LARGE`), so the envelope carries that code rather than a notify-defined one. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    "notify.messages.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The message. */
            200: {
                headers: {
                    "x-ratelimit-limit": components["headers"]["RateLimitLimit"];
                    "x-ratelimit-remaining": components["headers"]["RateLimitRemaining"];
                    "x-ratelimit-reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description `VALIDATION_FAILED` — `id` is not a UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    "notify.messages.retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message re-queued. */
            200: {
                headers: {
                    "x-ratelimit-limit": components["headers"]["RateLimitLimit"];
                    "x-ratelimit-remaining": components["headers"]["RateLimitRemaining"];
                    "x-ratelimit-reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description `VALIDATION_FAILED` — `id` is not a UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description `NOT_RETRYABLE` — the message exists but is not in `failed` status (it is `queued`, `processing` or already `sent`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    "notify.templates.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All templates this instance ships with. */
            200: {
                headers: {
                    "x-ratelimit-limit": components["headers"]["RateLimitLimit"];
                    "x-ratelimit-remaining": components["headers"]["RateLimitRemaining"];
                    "x-ratelimit-reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
}
