/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the canonical OpenAPI document
         * @description Returns this service's repository-root OpenAPI 3.1 document byte-for-byte.
         */
        get: operations["webhookout.openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["webhookOut.health.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks the database and reports the in-process (or last-heartbeat-seen) worker status.
         *     The result is cached for up to 10 seconds.
         */
        get: operations["webhookOut.ready.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and API contract identification */
        get: operations["webhookOut.info.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Authenticated (`read` need) but, unlike every other `/v1/*` route, **not** subject to this
         *     service's own per-key rate limiter — it is registered outside the `/v1` sub-app that the
         *     rate-limit plugin wraps, and its path is literally `/metrics`, not `/v1/metrics`.
         */
        get: operations["webhookOut.metrics.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions */
        get: operations["webhookOut.subscriptions.list"];
        put?: never;
        /**
         * Create a subscription
         * @description Creates a subscription and returns its brand-new signing secret. **The secret is shown
         *     only here and in the `rotate` response — it cannot be retrieved again afterward** (only a
         *     sealed form is stored).
         */
        post: operations["webhookOut.subscriptions.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        /** Get a subscription */
        get: operations["webhookOut.subscriptions.get"];
        put?: never;
        post?: never;
        /**
         * Delete a subscription
         * @description Also deletes, by database cascade, every delivery queued or recorded for it.
         */
        delete: operations["webhookOut.subscriptions.delete"];
        options?: never;
        head?: never;
        /**
         * Update a subscription
         * @description Partial update; at least one field is required. `enabled: true` resumes the subscription
         *     (including from the automatic `disabled` state, resetting the consecutive-failure
         *     counter); `enabled: false` pauses it.
         */
        patch: operations["webhookOut.subscriptions.patch"];
        trace?: never;
    };
    "/v1/subscriptions/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a subscription's signing secret
         * @description Issues a brand-new signing secret immediately. **The plaintext secret is returned only in
         *     this response — it is never retrievable again afterward.** The previous secret keeps
         *     signing a second, parallel `v1` HMAC signature on outgoing deliveries until
         *     `previousValidUntil` (governed by `PREV_SECRET_GRACE_HOURS`; `null` when the grace period
         *     is configured to zero), so a receiver can roll its own verification key over without
         *     dropping in-flight deliveries.
         */
        post: operations["webhookOut.subscriptions.rotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test delivery
         * @description Queues one synthetic `webhook.test` event for this subscription only, regardless of its
         *     event patterns or status (a paused subscription still gets it queued; it is sent once
         *     resumed). Async: `202` is a durability guarantee that the delivery is queued, not that it
         *     has been attempted yet.
         */
        post: operations["webhookOut.subscriptions.test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-queue events in a time window for this subscription
         * @description Re-queues every already-published, non-test event in `[from, to)` that matches this
         *     subscription's patterns as a brand-new delivery — existing deliveries for those events are
         *     untouched, so the receiver will see repeated event ids and must de-duplicate itself.
         *     `to` defaults to now. Distinct from `test` (queues one synthetic event) and from automatic
         *     retry (reuses the same delivery id) — this always creates new delivery rows, one per
         *     matching event, and the response reports only a count, not the events or deliveries
         *     themselves.
         */
        post: operations["webhookOut.subscriptions.replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a subscription's deliveries */
        get: operations["webhookOut.subscriptions.listDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published events
         * @description Newest first; test events (from `test`/`replay`-adjacent synthetic publishes) are excluded.
         */
        get: operations["webhookOut.events.list"];
        put?: never;
        /**
         * Publish an event
         * @description Inserts the event and fans it out to a `deliveries` row for every currently-active
         *     subscription whose patterns match, in the same database transaction as the event insert —
         *     a `202` is a durability guarantee for every matching subscriber at the time of publish, not
         *     just an ack of receipt.
         *
         *     With `idempotencyKey`, a repeat publish from the same API key (`source`) and the same key
         *     returns the **original** event and queues nothing new: `duplicate: true` and HTTP `200`
         *     instead of `202`. `deliveries` in the response is always an integer **count** of the
         *     deliveries created (or, for a duplicate, already existing) for this event — never an array
         *     of delivery objects.
         */
        post: operations["webhookOut.events.publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event and its deliveries */
        get: operations["webhookOut.events.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List distinct published event types
         * @description Aggregated counts and last-seen time per type, over all non-test events ever published.
         */
        get: operations["webhookOut.eventTypes.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deliveries */
        get: operations["webhookOut.deliveries.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a delivery */
        get: operations["webhookOut.deliveries.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries/{id}/redeliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a fresh delivery of the same event
         * @description Queues a brand-new delivery (new delivery id, attempt counter reset) of the same event to
         *     the same subscription — e.g. after fixing the receiver. The original delivery row is
         *     untouched. Distinct from automatic retry (same delivery id) and from `replay` (a whole time
         *     window, not one delivery).
         */
        post: operations["webhookOut.deliveries.redeliver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a queued delivery
         * @description Only `pending` and `retrying` deliveries can be cancelled; a `running` attempt cannot be interrupted.
         */
        post: operations["webhookOut.deliveries.cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate subscription/event/delivery/worker statistics
         * @description `last24h`/`recentFailures`/`avgDurationMs24h` are computed over a fixed trailing 24-hour window.
         */
        get: operations["webhookOut.stats.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                /** @description Present only on some errors (e.g. VALIDATION_FAILED's field-level list). */
                details?: unknown;
            };
        };
        SubscriptionId: string;
        EventId: string;
        /** @description A delivery id or event sequence number, as a decimal string (path/query parameters are always strings). */
        IntIdString: string;
        /** @description Page size, 1-200. Defaults to 50 when omitted. */
        Limit: string;
        /** Format: date-time */
        IsoDateTimeString: string;
        /** @enum {string} */
        SubscriptionStatus: "active" | "paused" | "disabled";
        /**
         * @description Exactly six values. `pending` (queued) → `running` (attempt in flight) → `succeeded` /
         *     `failed` (terminal) or `retrying` (scheduled backoff, back to `running` later); `cancelled`
         *     from `pending`/`retrying` only. No `skipped` state exists in this service (unlike
         *     scheduler's unrelated, 7-value run-status enum).
         * @enum {string}
         */
        DeliveryStatus: "pending" | "running" | "retrying" | "succeeded" | "failed" | "cancelled";
        /** @description Dot-separated lower-case segments, e.g. `order.paid`. */
        EventType: string;
        /**
         * @description One of three legal forms: an exact event type (`order.paid`), the bare wildcard `*`
         *     (matches everything), or a dot-terminated prefix wildcard (`order.*`, matches any type
         *     strictly longer than `order.` that starts with it). Not a general glob.
         */
        EventPattern: string;
        SubscriptionName: string;
        /**
         * @description Plaintext HMAC signing secret. Returned **only** at subscription creation and at
         *     `rotate` — it is sealed at rest afterward and cannot be retrieved again through any other
         *     endpoint.
         */
        SigningSecret: string;
        /**
         * @description Custom headers sent with every delivery to this subscription. Names must match
         *     `^x-[a-z0-9-]{1,60}$` (case-insensitive, stored lower-cased) and must not start with
         *     `x-webhook-` (reserved for this service's own signature/id/timestamp headers). Values must
         *     be printable ASCII, up to 1024 characters.
         */
        Headers: {
            [key: string]: string;
        };
        CreateSubscriptionBody: {
            name: components["schemas"]["SubscriptionName"];
            /** @description Delivery target URL; validated against this service's outbound-target policy (scheme, private-network rules). */
            url: string;
            events: components["schemas"]["EventPattern"][];
            description?: string;
            headers?: components["schemas"]["Headers"];
            /** @description Default true. `false` creates the subscription already paused. */
            enabled?: boolean;
            /** @description Best-effort in-order delivery for this subscription (at most one in-flight delivery at a time). Default false. */
            ordered?: boolean;
        };
        PatchSubscriptionBody: {
            name?: components["schemas"]["SubscriptionName"];
            url?: string;
            events?: components["schemas"]["EventPattern"][];
            description?: string;
            headers?: components["schemas"]["Headers"];
            /** @description true resumes (also from `disabled`, resetting the failure counter); false pauses. */
            enabled?: boolean;
            ordered?: boolean;
        };
        Subscription: {
            id: components["schemas"]["SubscriptionId"];
            name: string;
            description: string;
            url: string;
            events: components["schemas"]["EventPattern"][];
            headers: {
                [key: string]: string;
            };
            status: components["schemas"]["SubscriptionStatus"];
            consecutiveFailures: number;
            /** Format: date-time */
            lastDeliveryAt: string | null;
            /** @enum {string|null} */
            lastStatus: "succeeded" | "failed" | null;
            /**
             * Format: date-time
             * @description When the previous signing secret stops being accepted (null if no rotation grace is active).
             */
            secretRotatedUntil: string | null;
            /** @description API key id that created this subscription. */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            ordered: boolean;
        };
        SubscriptionWithSecret: {
            subscription: components["schemas"]["Subscription"];
            secret: components["schemas"]["SigningSecret"];
        };
        Event: {
            id: components["schemas"]["EventId"];
            type: string;
            /** @description Arbitrary JSON payload as published. */
            data: unknown;
            idempotencyKey: string | null;
            /** @description API key id that published this event. */
            source: string;
            /** @description True for a synthetic event created by `POST /v1/subscriptions/{id}/test`. */
            test: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        EventPublishResult: {
            event: components["schemas"]["Event"];
            /** @description Count of deliveries created (new publish) or already existing (idempotent duplicate) for this event. An integer count, never an array of delivery objects. */
            deliveries: number;
            /** @description True when this call matched an existing `idempotencyKey` from the same API key and returned the original event instead of publishing a new one. */
            duplicate: boolean;
        };
        Attempt: {
            n: number;
            /** Format: date-time */
            startedAt: string;
            durationMs: number;
            httpStatus: number | null;
            error: string | null;
        };
        Delivery: {
            id: number;
            eventId: components["schemas"]["EventId"];
            subscriptionId: components["schemas"]["SubscriptionId"];
            status: components["schemas"]["DeliveryStatus"];
            /** @description Attempts made so far. */
            attempt: number;
            /** @description retryScheduleSec.length + 1, fixed at delivery creation. */
            maxAttempts: number;
            /** Format: date-time */
            nextAttemptAt: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            durationMs: number | null;
            httpStatus: number | null;
            /** @description Truncated response body of the most recent attempt. */
            response: string | null;
            error: string | null;
            attempts: components["schemas"]["Attempt"][];
            /** Format: date-time */
            createdAt: string;
        };
        DeliveryListResponse: {
            items: components["schemas"]["Delivery"][];
            /** @description Keyset pagination cursor (a delivery id as a string) — pass as `before` to fetch the next page. `null` on the last page. */
            nextBefore: string | null;
        };
        Stats: {
            subscriptions: {
                active: number;
                paused: number;
                disabled: number;
            };
            events: {
                total: number;
                last24h: number;
            };
            deliveries: {
                byStatus: components["schemas"]["DeliveryStatusCounts"];
                last24h: components["schemas"]["DeliveryStatusCounts"];
                backlog: {
                    queued: number;
                    /** Format: date-time */
                    oldestAt: string | null;
                };
                avgDurationMs24h: number | null;
                topFailures24h: {
                    subscriptionId: components["schemas"]["SubscriptionId"];
                    failed: number;
                }[];
            };
            worker: {
                running: boolean;
                inFlight: number;
                concurrency: number;
                /**
                 * @description Process-local counters since this process started, or `null` when this process has
                 *     no in-process worker (API-only role) — a deliberate `null`, not a misleading zero,
                 *     since this process itself never finished a delivery.
                 */
                sinceStart: null | {
                    succeeded: number;
                    failed: number;
                    retried: number;
                    disabled: number;
                };
            };
        };
        DeliveryStatusCounts: {
            pending: number;
            running: number;
            retrying: number;
            succeeded: number;
            failed: number;
            cancelled: number;
        };
    };
    responses: {
        /** @description `UNAUTHORIZED` — missing or unrecognized API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `FORBIDDEN` — the presented key's role does not satisfy this route's need. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `RATE_LIMITED` — this API key exceeded its per-minute request budget. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `VALIDATION_FAILED` — request failed JSON Schema validation (only reachable reason for a 400 at this route). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `SUBSCRIPTION_NOT_FOUND` — no subscription with this id. */
        SubscriptionNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `SUBSCRIPTION_EXISTS` — a subscription with this name already exists. */
        SubscriptionExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `EVENT_NOT_FOUND` — no event with this id. */
        EventNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `DELIVERY_NOT_FOUND` — no delivery with this id. */
        DeliveryNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `DELIVERY_NOT_CANCELLABLE` — the delivery is not `pending` or `retrying` (e.g. already `running` or terminal), so it cannot be cancelled. */
        DeliveryNotCancellable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `EVENT_TOO_LARGE` — the JSON-encoded `data` exceeds this instance's configured `MAX_EVENT_BYTES`. */
        EventTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "webhookout.openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical OpenAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/yaml": string;
                };
            };
        };
    };
    "webhookOut.health.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. No dependency check is performed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    "webhookOut.ready.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. `worker` is `"running"` or `"stopped"`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "worker": "running"
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        /** @enum {string} */
                        worker: "running" | "stopped";
                    };
                };
            };
            /** @description Not ready (dependency check failed). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unavailable",
                     *       "error": "database unreachable"
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        status: "unavailable";
                        error: string;
                    };
                };
            };
        };
    };
    "webhookOut.info.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        service: "webhook-out";
                        /** @description This service's own package.json semver. */
                        version: string;
                        /** @constant */
                        apiVersion: "v1";
                        /**
                         * @description Static list of always-on capabilities.
                         * @example [
                         *       "replay",
                         *       "rotate",
                         *       "test-delivery",
                         *       "redeliver"
                         *     ]
                         */
                        capabilities: string[];
                        /** @description Current database schema version (PRAGMA user_version). */
                        schemaVersion: number;
                        /** @description Version of the shared @atc-web/service-core package actually running. */
                        serviceCore: string;
                    };
                };
            };
        };
    };
    "webhookOut.metrics.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # HELP webhook_subscriptions Subscriptions by status.
                     *     # TYPE webhook_subscriptions gauge
                     *     webhook_subscriptions{status="active"} 3
                     */
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "webhookOut.subscriptions.list": {
        parameters: {
            query?: {
                /** @description Substring match against name, description or URL. */
                q?: string;
                status?: components["schemas"]["SubscriptionStatus"];
                /** @description Only subscriptions whose `events` array contains exactly this pattern string. */
                event?: string;
                limit?: components["schemas"]["Limit"];
                /** @description Opaque keyset cursor; pass back the previous page's `nextCursor` (a subscription name). */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Subscription"][];
                        nextCursor: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description `/v1/subscriptions/{id}` of the new subscription. */
                    location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionWithSecret"];
                };
            };
            /**
             * @description One of: `VALIDATION_FAILED` (request body fails the JSON Schema), `INVALID_URL`
             *     (target URL rejected by the outbound-target guard — scheme, host or private-network
             *     policy), `INVALID_PATTERN` (an `events` entry is not an exact type, `*`, or a
             *     `name.*` prefix), `INVALID_HEADER` (a custom header name/value is not allowed).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SubscriptionExists"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["Subscription"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SubscriptionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; no content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SubscriptionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSubscriptionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["Subscription"];
                    };
                };
            };
            /**
             * @description One of: `VALIDATION_FAILED`, `INVALID_URL`, `INVALID_PATTERN`, `INVALID_HEADER` — same
             *     meanings as on create.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SubscriptionNotFound"];
            /** @description `SUBSCRIPTION_EXISTS` — the patched `name` collides with another subscription. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.rotate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["Subscription"];
                        secret: components["schemas"]["SigningSecret"];
                        /** Format: date-time */
                        previousValidUntil: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SubscriptionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted and queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event: components["schemas"]["Event"];
                        delivery: components["schemas"]["Delivery"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SubscriptionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    from: components["schemas"]["IsoDateTimeString"];
                    to?: components["schemas"]["IsoDateTimeString"];
                };
            };
        };
        responses: {
            /** @description Accepted; every matching event has already been queued as a new delivery. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "queued": 42
                     *     }
                     */
                    "application/json": {
                        /** @description Count of newly-queued deliveries, not an array of them. */
                        queued: number;
                    };
                };
            };
            /**
             * @description One of: `VALIDATION_FAILED` (`from`/`to` missing or not an ISO 8601-shaped string per
             *     the request schema), `INVALID_RANGE` (`from`/`to` fails `Date.parse`, or `to` is not
             *     after `from`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SubscriptionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.subscriptions.listDeliveries": {
        parameters: {
            query?: {
                status?: components["schemas"]["DeliveryStatus"];
                event?: components["schemas"]["EventId"];
                limit?: components["schemas"]["Limit"];
                /** @description Keyset pagination — the previous page's `nextBefore`. */
                before?: components["schemas"]["IntIdString"];
                /**
                 * @description Accepted by the request schema but ignored: the `{id}` path segment always determines
                 *     the subscription filter on this route.
                 */
                subscription?: components["schemas"]["SubscriptionId"];
            };
            header?: never;
            path: {
                id: components["schemas"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryListResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SubscriptionNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.events.list": {
        parameters: {
            query?: {
                type?: components["schemas"]["EventType"];
                limit?: components["schemas"]["Limit"];
                /** @description Keyset pagination on the internal event sequence — the previous page's `nextBefore`. */
                before?: components["schemas"]["IntIdString"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Event"][];
                        nextBefore: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.events.publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type: components["schemas"]["EventType"];
                    /** @description Arbitrary JSON payload, stored and echoed back as-is. Defaults to `null`. */
                    data?: unknown;
                    idempotencyKey?: string;
                };
            };
        };
        responses: {
            /** @description Idempotent duplicate — the original event is returned; nothing new was queued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "event": {
                     *         "id": "evt_1a2b3c4d5e6f7081",
                     *         "type": "order.paid",
                     *         "data": {
                     *           "orderId": 42
                     *         },
                     *         "idempotencyKey": "order-42-paid",
                     *         "source": "key_publisher",
                     *         "test": false,
                     *         "createdAt": "2026-09-18T10:00:00.000Z"
                     *       },
                     *       "deliveries": 3,
                     *       "duplicate": true
                     *     }
                     */
                    "application/json": components["schemas"]["EventPublishResult"];
                };
            };
            /** @description New event, accepted and queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "event": {
                     *         "id": "evt_1a2b3c4d5e6f7081",
                     *         "type": "order.paid",
                     *         "data": {
                     *           "orderId": 42
                     *         },
                     *         "idempotencyKey": null,
                     *         "source": "key_publisher",
                     *         "test": false,
                     *         "createdAt": "2026-09-18T10:00:00.000Z"
                     *       },
                     *       "deliveries": 3,
                     *       "duplicate": false
                     *     }
                     */
                    "application/json": components["schemas"]["EventPublishResult"];
                };
            };
            /** @description One of `VALIDATION_FAILED` or `INVALID_EVENT_TYPE` (`type` is not dot-separated lower-case segments). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description `FORBIDDEN` — the presented key's role does not satisfy the `publish` need (i.e. it is
             *     not `publish`, `write` or `readwrite`).
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            413: components["responses"]["EventTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.events.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event: components["schemas"]["Event"];
                        /** @description Every delivery this event ever produced, across all subscriptions. */
                        deliveries: components["schemas"]["Delivery"][];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["EventNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.eventTypes.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            type: string;
                            count: number;
                            /** Format: date-time */
                            lastAt: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.deliveries.list": {
        parameters: {
            query?: {
                status?: components["schemas"]["DeliveryStatus"];
                subscription?: components["schemas"]["SubscriptionId"];
                event?: components["schemas"]["EventId"];
                limit?: components["schemas"]["Limit"];
                /** @description Keyset pagination — the previous page's `nextBefore`. */
                before?: components["schemas"]["IntIdString"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryListResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.deliveries.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["IntIdString"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        delivery: components["schemas"]["Delivery"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["DeliveryNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.deliveries.redeliver": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["IntIdString"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted and queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        delivery: components["schemas"]["Delivery"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["DeliveryNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.deliveries.cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["IntIdString"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        delivery: components["schemas"]["Delivery"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["DeliveryNotFound"];
            409: components["responses"]["DeliveryNotCancellable"];
            429: components["responses"]["RateLimited"];
        };
    };
    "webhookOut.stats.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
