/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Always returns 200 once the process is accepting connections. No dependency checks.
         */
        get: operations["ratelimit.health.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Pings the SQLite database (`db.ping()`); result cached 10s. 200 when the ping succeeds, 503 otherwise. No `extra` fields are merged into the healthy body — the response is exactly `{status:'ok'}`.
         */
        get: operations["ratelimit.ready.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service identity and capabilities
         * @description Static identity and capability information. Registered directly on the app, outside the `/v1` sub-app that carries API-key auth and the self-throttle — unauthenticated and never rate-limited, despite the `/v1` prefix in its path.
         */
        get: operations["ratelimit.info.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Prometheus text exposition format: policy count, decisions since process start per policy and decision, live counter-row count, database size, process uptime. Requires a `read` (or `readwrite`) API key. Registered as its own plugin, outside the `/v1` sub-app — authenticated like every other route, but **exempt from the self-throttle** (the `@fastify/rate-limit` plugin only wraps `/v1`), the same platform-wide convention every service with a `/metrics` route follows so a fixed-schedule Prometheus scraper is never itself throttled.
         */
        get: operations["ratelimit.metrics.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check and consume one subject's quota against one policy
         * @description Evaluates every window of the effective limit set (the subject's active override, if any, else the policy's own limits) and, unless `peek: true`, atomically consumes `cost` units (default 1) when every window allows it — a denied check never consumes anything.
         *
         *     **HTTP `200` is returned for both an allow and a deny.** The business decision is the body's `allowed` field, never the HTTP status. This is deliberate, not an oversight: only this service's own self-throttle (see `components.responses.RateLimited`) ever produces an HTTP `429` here, and it is a completely separate mechanism from a policy's own limit — a `429` means "you called `ratelimit` itself too often," never "this subject is over its policy limit." No `Retry-After` HTTP header is ever set for a business-level denial; the domain-level `retryAfter` on the returned `Decision` is body-only.
         *
         *     Requires a `check` (or `readwrite`) API key, scoped to the target policy (a key with a `policies` allowlist that does not include `policy` gets `403 FORBIDDEN`, checked before the policy is even looked up).
         */
        post: operations["ratelimit.check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check and consume several (policy, subject) pairs as one atomic unit
         * @description Same all-or-nothing atomicity and the same `200`-even-when-denied contract as `POST /v1/check` (see that operation's description — it applies identically here): the top-level `allowed` and every `results[i].allowed` are body-level business decisions, never reflected in the HTTP status, and never produce an HTTP `429` by themselves. Counters move only when **every** check in the batch allows its cost; if any one is denied, every result in the response comes back with `allowed: false` (the ones that individually would have passed are still reported as not-allowed, since nothing was consumed for them either).
         *
         *     Requires a `check` (or `readwrite`) API key, scoped to every policy named in `checks` (the first out-of-scope policy found gets `403 FORBIDDEN`).
         *
         *     `400 DUPLICATE_CHECK` is a genuinely overloaded error code with two unrelated trigger conditions — do not assume it always means a literal duplicate: (1) the batch has more than `MAX_BATCH` entries (config-configurable, default 20 — note the request body schema itself allows up to 100 entries, so a batch that passes JSON-Schema validation can still be rejected here), or (2) the same `(policy, subject)` pair appears twice in `checks`.
         */
        post: operations["ratelimit.checkBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Give back units consumed by an earlier check
         * @description For an operation that consumed quota via `POST /v1/check` and then itself failed, releases `cost` units (default 1) back into the window they were actually consumed from. `consumedAt`, when given, should be the `consumedAt` value the original `Decision` returned — this targets the window that was truly consumed even after it has rolled over; omitting it targets whichever window `now` falls in, which is only correct when the release happens inside the same window the original check consumed. Evaluated at `now`, and — like `/check` and `/check/batch` — always `200`, with the resulting `Decision` reflecting the state after the release; there is no failure mode here that maps to a body-level `allowed: false` distinct from the returned decision's own fields.
         *
         *     Requires a `check` (or `readwrite`) API key, scoped to the target policy.
         */
        post: operations["ratelimit.release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List policies visible to this API key
         * @description Requires a `read` (or `readwrite`) API key. Filtered to the key's own `policies` scope when it has one (`policies: null` on the key sees every policy). Never scope-forbidden — an out-of-scope policy is silently omitted rather than causing a `403`.
         */
        get: operations["ratelimit.policies.list"];
        put?: never;
        /**
         * Create a policy
         * @description Requires a `write` (or `readwrite`) API key, scoped to the new policy's own name. Returns `Location: /v1/policies/{name}` on success.
         */
        post: operations["ratelimit.policies.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one policy
         * @description Requires a `read` (or `readwrite`) API key, scoped to this policy.
         */
        get: operations["ratelimit.policies.get"];
        put?: never;
        post?: never;
        /**
         * Delete a policy
         * @description Requires a `write` (or `readwrite`) API key, scoped to this policy. Deletes the policy along with its overrides, counters and statistics. No response body.
         */
        delete: operations["ratelimit.policies.delete"];
        options?: never;
        head?: never;
        /**
         * Update a policy's description and/or limits
         * @description Requires a `write` (or `readwrite`) API key, scoped to this policy. At least one of `description`/`limits` must be given. Existing overrides and counters are unaffected by a limits change; only future checks are evaluated against the new limits.
         */
        patch: operations["ratelimit.policies.patch"];
        trace?: never;
    };
    "/v1/policies/{name}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hourly allowed/denied series for a policy
         * @description Requires a `read` (or `readwrite`) API key, scoped to this policy. Hourly series for the last `hours` hours (default 24, max 720 = 30 days), gaps filled with zeros.
         */
        get: operations["ratelimit.policies.getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{name}/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subjects with the highest usage in one window of a policy
         * @description Requires a `read` (or `readwrite`) API key, scoped to this policy. `window` defaults to the policy's first (shortest) configured window when omitted; a `window` value that is not one of the policy's configured windows is `400 UNKNOWN_WINDOW`.
         */
        get: operations["ratelimit.policies.getTop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{name}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a policy's subject overrides
         * @description Requires a `read` (or `readwrite`) API key, scoped to this policy. Offset-paginated.
         */
        get: operations["ratelimit.overrides.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{name}/overrides/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or replace a subject's override
         * @description Requires a `write` (or `readwrite`) API key, scoped to this policy. Upsert — always succeeds when the policy exists and the body is valid, whether or not an override already exists for this subject (never `409`). A `limits` entry with `limit: 0` hard-blocks the subject on that window.
         */
        put: operations["ratelimit.overrides.set"];
        post?: never;
        /**
         * Remove a subject's override
         * @description Requires a `write` (or `readwrite`) API key, scoped to this policy. `404 OVERRIDE_NOT_FOUND` when no override exists for this subject (checked after the policy itself is confirmed to exist, so a missing policy still yields `404 POLICY_NOT_FOUND`).
         */
        delete: operations["ratelimit.overrides.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{name}/subjects/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current usage of one subject, without consuming
         * @description Requires a `read` (or `readwrite`) API key, scoped to this policy. A peek: `remaining` in the returned `usage.limits[]` is what is left right now, and no counters are touched. Also returns the subject's active override, if any.
         */
        get: operations["ratelimit.subjects.getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{name}/subjects/{subject}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Forget every counter of a subject
         * @description Requires a `write` (or `readwrite`) API key, scoped to this policy. Unlike the other deletes in this API, this returns `200` with the count of counter rows removed, not `204` — there is no separate resource whose absence a `204` would represent, only a count.
         */
        delete: operations["ratelimit.subjects.resetUsage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate statistics across every policy visible to this API key
         * @description Requires a `read` (or `readwrite`) API key. Scoped the same way as `GET /v1/policies` — only policies within the key's own `policies` allowlist (or every policy, when unscoped) contribute to the totals and `items`.
         */
        get: operations["ratelimit.stats.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: Record<string, never> | unknown[];
            };
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @description Present only when status is unavailable. */
            error?: string;
        };
        InfoResponse: {
            /** @constant */
            service: "ratelimit";
            /** @description ratelimit's own package.json version. */
            version: string;
            /** @constant */
            apiVersion: "v1";
            /**
             * @description Static list — always exactly these three, does not vary by deployment.
             * @example [
             *       "policy-windows",
             *       "overrides",
             *       "usage-stats"
             *     ]
             */
            capabilities: string[];
            /** @description The database's current schema version (SQLite `PRAGMA user_version`). */
            schemaVersion: number;
            /** @description The @atc-web/service-core version actually running. */
            serviceCore: string;
        };
        /** @example api.requests */
        PolicyNameValue: string;
        /**
         * @description No control characters (0x00-0x1F, 0x7F).
         * @example user-42
         */
        SubjectValue: string;
        Limit: {
            /** @description Window size in seconds. */
            window: number;
            /** @description Units allowed per window. 0 hard-blocks every check against this window. */
            limit: number;
        };
        /** @description Sorted by window ascending once stored. Distinct windows only. */
        Limits: components["schemas"]["Limit"][];
        /** @description State of one window for one subject, evaluated at the decision's `consumedAt`. */
        LimitState: {
            /** @description Window size in seconds. */
            window: number;
            limit: number;
            /** @description Sliding-window usage estimate (weighted blend of the previous and current window's counts). */
            used: number;
            remaining: number;
            /** @description Whether the requested cost fit in this window alone. */
            allowed: boolean;
            /**
             * Format: date-time
             * @description End of the current window.
             */
            resetAt: string;
            /** @description Seconds until the requested cost would fit. Null when this window is hard-blocked (limit 0). */
            retryAfter: number | null;
        };
        /** @description The result of a check, batch-check entry, or release. `limit`/`remaining`/`resetAt`/`retryAfter` summarize the single most restrictive window in `limits` (least `remaining` when allowed; the blocked or longest-wait window when denied) — always inspect `limits[]` directly for per-window detail. */
        Decision: {
            policy: string;
            subject: string;
            /** @description The business decision. HTTP status is always 200 regardless of this value. */
            allowed: boolean;
            /** @description Units this decision consumed (0 for a peek or a release). */
            cost: number;
            /**
             * @description Whether the effective limits came from the policy itself or an active subject override.
             * @enum {string}
             */
            source: "policy" | "override";
            /** @description True when the effective limits include a limit-0 window (a hard block), independent of `allowed`. */
            blocked: boolean;
            /** @description Limit of the most restrictive window. */
            limit: number;
            remaining: number;
            /** Format: date-time */
            resetAt: string;
            /** @description Seconds until this subject's most restrictive window would allow the cost; 0 when `allowed`. Body-only — never mirrored as an HTTP `Retry-After` header for a business-level decision. */
            retryAfter: number | null;
            limits: components["schemas"]["LimitState"][];
            /**
             * Format: date-time
             * @description The instant this decision was evaluated at. Pass back as `release`'s `consumedAt` to target the window that was actually consumed, even after it has rolled over.
             */
            consumedAt: string;
        };
        CheckInput: {
            policy: components["schemas"]["PolicyNameValue"];
            subject: components["schemas"]["SubjectValue"];
            /** @description Units to consume. Default 1. */
            cost?: number;
        };
        CheckRequest: {
            policy: components["schemas"]["PolicyNameValue"];
            subject: components["schemas"]["SubjectValue"];
            /** @description Units to consume. Default 1. */
            cost?: number;
            /** @description Evaluate without consuming. Default false. */
            peek?: boolean;
        };
        CheckBatchRequest: {
            /** @description Schema allows up to 100 entries; MAX_BATCH (default 20) is enforced at the domain layer — see this operation's description. */
            checks: components["schemas"]["CheckInput"][];
            /** @description Evaluate without consuming, for every entry. Default false. */
            peek?: boolean;
        };
        CheckBatchResponse: {
            /** @description True only if every entry in results was allowed. */
            allowed: boolean;
            results: components["schemas"]["Decision"][];
        };
        ReleaseRequest: {
            policy: components["schemas"]["PolicyNameValue"];
            subject: components["schemas"]["SubjectValue"];
            /** @description Units to give back. Default 1. */
            cost?: number;
            /** @description ISO 8601 instant the units were originally consumed at. Default now. */
            consumedAt?: string;
        };
        CreatePolicyRequest: {
            name: components["schemas"]["PolicyNameValue"];
            description?: string;
            limits: components["schemas"]["Limits"];
        };
        PatchPolicyRequest: {
            description?: string;
            limits?: components["schemas"]["Limits"];
        };
        OverrideRequest: {
            limits: components["schemas"]["Limits"];
            note?: string;
            /** @description ISO 8601 instant, must be in the future. Null or omitted means no expiry. */
            expiresAt?: string | null;
        };
        Policy: {
            name: string;
            description: string;
            limits: components["schemas"]["Limits"];
            /** @description Count of active subject overrides for this policy. */
            overrides: number;
            /** @description Distinct subjects with a live counter window right now. */
            activeSubjects: number;
            last24h: {
                allowed: number;
                denied: number;
            };
            /** @description API key id that created this policy. */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Override: {
            policy: string;
            subject: string;
            limits: components["schemas"]["Limits"];
            /** @description True when limits includes a limit-0 window. */
            blocked: boolean;
            note: string;
            /** Format: date-time */
            expiresAt: string | null;
            /** @description True when expiresAt is set and in the past, as of the response's own evaluation instant. */
            expired: boolean;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PolicyResponse: {
            policy: components["schemas"]["Policy"];
        };
        PoliciesListResponse: {
            items: components["schemas"]["Policy"][];
        };
        StatsResponse: {
            hours: number;
            /** @description Sum of allowed across the series. */
            allowed: number;
            /** @description Sum of denied across the series. */
            denied: number;
            series: {
                /**
                 * Format: date-time
                 * @description Start of this hour bucket.
                 */
                hour: string;
                allowed: number;
                denied: number;
            }[];
        };
        TopResponse: {
            /** @description The resolved window (seconds) these results were computed against. */
            window: number;
            /** @description That window's configured limit. */
            limit: number;
            items: {
                subject: string;
                /** @description Sliding-window usage estimate. */
                used: number;
            }[];
        };
        OverridesListResponse: {
            items: components["schemas"]["Override"][];
            /** @description Total overrides for this policy, independent of limit/offset. */
            total: number;
            limit: number;
            offset: number;
        };
        OverrideResponse: {
            override: components["schemas"]["Override"];
        };
        SubjectUsageResponse: {
            usage: components["schemas"]["Decision"];
            override: components["schemas"]["Override"] | null;
        };
        ResetUsageResponse: {
            /** @description Counter rows removed. */
            removed: number;
        };
        GlobalStatsResponse: {
            /** @description Count of policies visible to this key. */
            policies: number;
            last24h: {
                allowed: number;
                denied: number;
            };
            /** @description Live counter rows across every policy (unscoped by key). */
            counters: number;
            /** @description Database file size in bytes (unscoped by key). */
            dbBytes: number;
            items: {
                name: string;
                limits: components["schemas"]["Limits"];
                overrides: number;
                activeSubjects: number;
                last24h: {
                    allowed: number;
                    denied: number;
                };
            }[];
        };
    };
    responses: {
        /** @description Bearer token missing or does not match any configured API key. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate": components["headers"]["WWWAuthenticate"];
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "missing or invalid API key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The API key's role does not satisfy this route's requirement, or (on a policy-scoped route) the key's policies allowlist does not include the named policy. */
        Forbidden: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "this API key has no access to policy \"api.requests\""
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request failed JSON-Schema validation (path/query/body). */
        ValidationFailed: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_FAILED",
                 *         "message": "body/name must match pattern \"^[a-z0-9]+([.\\-_][a-z0-9]+)*$\"",
                 *         "details": [
                 *           {
                 *             "path": "/name",
                 *             "message": "must match pattern \"^[a-z0-9]+([.\\-_][a-z0-9]+)*$\"",
                 *             "params": {}
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No policy with this name exists. */
        PolicyNotFound: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "POLICY_NOT_FOUND",
                 *         "message": "policy \"api.requests\" not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description A policy with this name already exists. */
        PolicyExists: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "POLICY_EXISTS",
                 *         "message": "policy \"api.requests\" already exists"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The policy exists but has no override for this subject. */
        OverrideNotFound: {
            headers: {
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "OVERRIDE_NOT_FOUND",
                 *         "message": "no override for \"user-42\" in policy \"api.requests\""
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description This service's own self-throttle (`@fastify/rate-limit`, keyed by API-key id, default 6000 requests/minute via `RATE_LIMIT_MAX`) rejected the request. Unrelated to any policy's own limits — a `200` with `allowed: false` is how a policy-level denial is reported, never this `429`. This is the only response in this API that ever carries a `Retry-After` header. */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "rate limit exceeded, retry in 1 minute"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Policy name. */
        PolicyName: components["schemas"]["PolicyNameValue"];
        /** @description Subject identifier (opaque to this service — a user id, an IP, an API key id, ...). */
        Subject: components["schemas"]["SubjectValue"];
    };
    requestBodies: never;
    headers: {
        /** @description Always set by ratelimit's response hook. */
        XContentTypeOptions: "nosniff";
        /** @description Always set by ratelimit's response hook. */
        CacheControl: "no-store";
        /** @description Present on every 401 response. */
        WWWAuthenticate: "Bearer";
        /** @description Path of the newly created policy. */
        Location: string;
        /** @description Seconds until the self-throttle window resets. Set **only** on the self-throttle's own `429` — never on a `200` business-level denial (that `retryAfter` is body-only, on the returned `Decision`/`LimitState`). */
        RetryAfter: number;
        /** @description The self-throttle's configured max requests per window (`RATE_LIMIT_MAX`, default 6000/minute). Set only on the self-throttle's own `429`. */
        XRateLimitLimit: number;
        /** @description Always `0` on the self-throttle's own `429` (the response that reports the limit was just exceeded). */
        XRateLimitRemaining: 0;
        /** @description Seconds until the self-throttle window resets. Set only on the self-throttle's own `429`. */
        XRateLimitReset: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "ratelimit.health.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "ratelimit.ready.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database ping succeeded (within the last 10s). */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database ping failed (within the last 10s). */
            503: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    "ratelimit.info.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity and capability information. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    "ratelimit.metrics.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics rendered as Prometheus text. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4; charset=utf-8": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "ratelimit.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description The check was evaluated — `allowed` may be `true` or `false`; both are a normal `200`, never an HTTP `429`. `blocked: true` means the effective limits include a `limit: 0` window, i.e. this subject is hard-blocked regardless of remaining budget elsewhere. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            /** @description Validation failed, or the cost could never fit one of the effective windows. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.checkBatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckBatchRequest"];
            };
        };
        responses: {
            /** @description Every check in the batch was evaluated. `allowed` (top-level) is true only if every entry in `results` was allowed; a `200` is returned regardless, never a `429`. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckBatchResponse"];
                };
            };
            /** @description Validation failed, a cost could never fit one of the effective windows (`COST_TOO_HIGH`), or `DUPLICATE_CHECK` — see this operation's description for its two distinct trigger conditions. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description State after the release, evaluated at `now`. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            /** @description Validation failed, cost out of range, or `consumedAt` is not a valid ISO 8601 date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.policies.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policies visible to this key. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliciesListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.policies.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePolicyRequest"];
            };
        };
        responses: {
            /** @description Policy created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation failed, or `limits` is invalid (see `INVALID_LIMITS`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["PolicyExists"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.policies.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The policy. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.policies.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy deleted. */
            204: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.policies.patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPolicyRequest"];
            };
        };
        responses: {
            /** @description The updated policy. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation failed (including an empty patch body), or `limits` is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.policies.getStats": {
        parameters: {
            query?: {
                /** @description Number of trailing hours to report, 1-720. Default 24. */
                hours?: string;
            };
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hourly allowed/denied series. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.policies.getTop": {
        parameters: {
            query?: {
                /** @description Window size in seconds, must match one of the policy's configured windows. Defaults to the policy's shortest window. */
                window?: string;
                /** @description Maximum subjects to return, 1-1000. Default 20. */
                limit?: string;
            };
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top subjects by usage in the resolved window. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopResponse"];
                };
            };
            /** @description Validation failed, or `window` does not match any configured window (`UNKNOWN_WINDOW`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.overrides.list": {
        parameters: {
            query?: {
                /** @description Page size, 1-1000. Default 50. */
                limit?: string;
                /** @description Rows to skip. Default 0. */
                offset?: string;
            };
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overrides for this policy. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverridesListResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.overrides.set": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
                /** @description Subject identifier (opaque to this service — a user id, an IP, an API key id, ...). */
                subject: components["parameters"]["Subject"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description The override as stored. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideResponse"];
                };
            };
            /** @description Validation failed, `limits` is invalid (`INVALID_LIMITS`), or `expiresAt` is not a future ISO 8601 date (also `INVALID_LIMITS`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.overrides.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
                /** @description Subject identifier (opaque to this service — a user id, an IP, an API key id, ...). */
                subject: components["parameters"]["Subject"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Override removed. */
            204: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The policy does not exist (`POLICY_NOT_FOUND`), or it exists but has no override for this subject (`OVERRIDE_NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.subjects.getUsage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
                /** @description Subject identifier (opaque to this service — a user id, an IP, an API key id, ...). */
                subject: components["parameters"]["Subject"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current usage and, if present, the active override. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectUsageResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.subjects.resetUsage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy name. */
                name: components["parameters"]["PolicyName"];
                /** @description Subject identifier (opaque to this service — a user id, an IP, an API key id, ...). */
                subject: components["parameters"]["Subject"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counters removed. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetUsageResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PolicyNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "ratelimit.stats.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate statistics. */
            200: {
                headers: {
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStatsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
