/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always `200` while the process is up. No dependency check.
         */
        get: operations["scheduler.health.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Runs `db.ping()`, cached for 10 seconds. `worker` reports `"running"`/`"stopped"`: from the in-process `Worker` in the combined role, or derived from the `worker_heartbeat` table (fresh within 4 heartbeat intervals) in the API-only role.
         */
        get: operations["scheduler.ready.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service and API contract identification
         * @description `capabilities` is a static, always-on list for this service (confirmed no config flag makes any of these instance-variable). `schemaVersion` is the database's real `PRAGMA user_version`.
         */
        get: operations["scheduler.info.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Authenticated (any role) but exempt from this service's own `/v1` rate limiter — a fixed, platform-wide convention so scraper traffic on a regular schedule is never throttled. Since-process-start counters (`scheduler_runs_finished_total`, `scheduler_attempts_retried_total`) report real zero, not an omitted metric, from an API-only process that never finished a run itself.
         */
        get: operations["scheduler.metrics.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description Sorted by name; keyset-paginated on name.
         */
        get: operations["scheduler.jobs.list"];
        put?: never;
        /** Create a job */
        post: operations["scheduler.jobs.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a job */
        get: operations["scheduler.jobs.get"];
        put?: never;
        post?: never;
        /**
         * Delete a job
         * @description Deletes the job and, by database cascade, all of its runs.
         */
        delete: operations["scheduler.jobs.delete"];
        options?: never;
        head?: never;
        /**
         * Partially update a job
         * @description Changing `schedule` or setting `enabled: true` on a paused job recomputes the next firing; setting `enabled: false` clears it. At least one property is required.
         */
        patch: operations["scheduler.jobs.patch"];
        trace?: never;
    };
    "/v1/jobs/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a job manually
         * @description Queues a new `pending` run immediately, regardless of the job's schedule or `enabled` bit. Refused with `409 RUN_ACTIVE` when the job already has a `pending`, `running` or `retrying` run — only one run may be in flight per job at a time.
         */
        post: operations["scheduler.jobs.run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a job's runs
         * @description Newest first, keyset-paginated by run id. `404 JOB_NOT_FOUND` when the job does not exist (checked before listing). The query schema also accepts a `job` filter (shared with `GET /v1/runs`'s schema), but any value supplied there has no effect: this route always filters by the `{name}` path parameter.
         */
        get: operations["scheduler.jobs.listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs across all jobs
         * @description Newest first, keyset-paginated by run id.
         */
        get: operations["scheduler.runs.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: operations["scheduler.runs.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a queued or retrying run
         * @description Only `pending` and `retrying` runs can be cancelled. A `running` run (an attempt currently in flight) cannot be interrupted through this or any other HTTP route — cancelling it returns `409 RUN_NOT_CANCELLABLE`, as does cancelling a run already in a terminal state (`succeeded`, `failed`, `skipped`, `cancelled`).
         */
        post: operations["scheduler.runs.cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedule/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview a cron schedule's upcoming firings
         * @description Cron schedules only — there is no equivalent preview for a one-shot (`at`) schedule, since a one-shot schedule has exactly one firing, itself.
         */
        get: operations["scheduler.schedule.preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/target-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured target key names
         * @description Names only (sorted), from `TARGET_KEYS` — never the secrets themselves. A job references one of these names via `targetKey` to have its outbound call carry that key's bearer token, instead of putting `Authorization` in `target.headers` (which is rejected).
         */
        get: operations["scheduler.targetKeys.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/timezones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported IANA timezone names
         * @description The full set of `Intl.supportedValuesOf('timeZone')` for this Node runtime.
         */
        get: operations["scheduler.timezones.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job and run statistics
         * @description `runs.last24h`/`avgDurationMs24h`/`topFailures24h` cover a fixed trailing 24-hour window. `worker.sinceStart` is `null` from an API-only process (no in-process `Worker` to read since-start counters from); `worker.inFlight` and `worker.running` are always real and durable either way (from the `runs` table / `worker_heartbeat`, not process memory).
         */
        get: operations["scheduler.stats.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable error code. */
                code: string;
                message: string;
                /** @description Present only for `VALIDATION_FAILED` (array of Ajv findings); otherwise absent. */
                details?: {
                    path?: string;
                    message?: string;
                    params?: Record<string, never>;
                }[];
            };
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        ReadyResponse: {
            /** @constant */
            status: "ok";
            /** @enum {string} */
            worker: "running" | "stopped";
        };
        ReadyUnavailableResponse: {
            /** @constant */
            status: "unavailable";
            /** @description The readiness check's failure message (e.g. the database ping error). */
            error: string;
        };
        InfoResponse: {
            /** @constant */
            service: "scheduler";
            /** @description This service's own package semver. */
            version: string;
            /** @constant */
            apiVersion: "v1";
            /**
             * @example [
             *       "cron-schedule",
             *       "one-off-schedule",
             *       "retry-backoff",
             *       "http-target"
             *     ]
             */
            capabilities: string[];
            /** @description Database schema version (`PRAGMA user_version`). */
            schemaVersion: number;
            /** @description Version of the installed `@atc-web/service-core` package actually running. */
            serviceCore: string;
        };
        JobNameValue: string;
        /**
         * @description The full run-status lattice for this service (7 values). `pending` -> `running` -> (`retrying` -> `running`)* -> one of `succeeded`/`failed`/`skipped`/`cancelled`. `running` is reached and left only by the worker's internal claim loop, never by any HTTP route. `skipped` is recorded when a scheduled firing lands while the previous run for that job is still active. This enum is confirmed distinct from webhook-out's 6-value delivery-status enum (which has no `skipped`).
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "retrying" | "succeeded" | "failed" | "skipped" | "cancelled";
        /** @description A job fires either on a cron schedule or once at a fixed instant. Provide **either** `cron` (with an optional `timezone`, defaulting to the server's `DEFAULT_TIMEZONE`) **or** `at` (an ISO 8601 date-time that must be strictly in the future). This JSON Schema does not itself enforce "exactly one of `cron`/`at`" or "at least one of" — both are additionalProperties:false object of optional fields, so an empty object or an object with both `cron` and `at` both pass schema validation. The domain layer enforces the real rule: if `cron` is present (a string) it is used and `at` is ignored, even when both are supplied; only when `cron` is absent is `at` considered; when neither is a string, the request fails with `400 INVALID_SCHEDULE` ("schedule needs either cron (with optional timezone) or at"). So in practice this is "at least one of `cron`/`at`", with `cron` silently taking priority over `at` when both are given — not "exactly one". */
        Schedule: {
            /** @description Five-field cron expression, or an `@hourly`/`@daily`/`@weekly`/`@monthly`/`@yearly`/`@annually`/`@midnight` alias. */
            cron?: string;
            /** @description IANA timezone name. Only meaningful together with `cron`; defaults to `DEFAULT_TIMEZONE` when omitted. */
            timezone?: string;
            /** @description ISO 8601 date-time (must start `YYYY-MM-DDT` and parse via `Date.parse`), strictly after the current time. Ignored when `cron` is also present. */
            at?: string;
        };
        /** @description The HTTP call a job's firing makes. All `INVALID_TARGET` triggers below are domain-layer checks, not expressible in JSON Schema alone (source: `NetGuard#check` and `JobService#target`). */
        Target: {
            /** @description Must be an absolute URL. Scheme must be `https:` (or `http:` only when the server's `TARGET_ALLOW_HTTP=true`) -> otherwise `INVALID_TARGET` ("scheme ... is not allowed"). Must not embed credentials (`user:pass@host`) -> `INVALID_TARGET` ("url must not contain credentials"). When the server configures `TARGET_ALLOWED_HOSTS`, the hostname must equal or be a subdomain of one of those entries -> `INVALID_TARGET` ("host ... is not in TARGET_ALLOWED_HOSTS"). DNS resolution and private/loopback-address rejection are **not** checked at job create/update time — only later, synchronously, when the worker actually calls the target — so a `201`/`200` here is not a guarantee the target is reachable or public. */
            url: string;
            /**
             * @description Defaults to `POST`. Stored upper-cased.
             * @enum {string}
             */
            method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "get" | "post" | "put" | "patch" | "delete";
            /** @description Extra headers on the outbound call. JSON Schema only bounds count/name-length/value- length; the domain layer additionally requires, per header (else `INVALID_TARGET`): the lower-cased name must match `^x-[a-z0-9-]{1,60}$` (custom `X-*` only — this is also where `Authorization` is rejected: use `targetKey` instead, never a header); the name must NOT start with `x-scheduler-` (reserved for this service's own internal use); and the value must be printable ASCII (`\x20`-`\x7e`), <=1024 characters. At most 10 headers total. */
            headers?: {
                [key: string]: string;
            };
            /** @description Any JSON value, sent as `application/json`. Rejected with `INVALID_TARGET` when `method` is `GET` or `DELETE` ("requests cannot carry a body"). When present and its JSON-encoded byte length exceeds the server's `MAX_BODY_BYTES`, rejected with `413 BODY_TOO_LARGE` instead. */
            body?: unknown;
        };
        RetryPolicy: {
            /** @description Retries after the first attempt (0 = none). Defaults to 3. Bounded server-side by `MAX_RETRIES`; a value above that bound is `INVALID_TARGET`. */
            max?: number;
            /** @description First retry delay in seconds, doubling per retry, capped at `MAX_BACKOFF_SEC`. Defaults to 30. A value above that server bound is `INVALID_TARGET`. */
            backoffSec?: number;
        };
        JobCreate: {
            name: components["schemas"]["JobNameValue"];
            description?: string;
            /** @description Normalized on save (trimmed, lower-cased, de-duplicated, sorted). */
            tags?: string[];
            /** @description Defaults to `true`. A disabled job has no `nextRunAt` and never fires on its own. */
            enabled?: boolean;
            schedule: components["schemas"]["Schedule"];
            target: components["schemas"]["Target"];
            /** @description Name of a configured `TARGET_KEYS` entry whose bearer token is sent with the outbound call. Must name a configured key, else `400 UNKNOWN_TARGET_KEY`. */
            targetKey?: string | null;
            /** @description Defaults to the server's `DEFAULT_TIMEOUT_MS`. Must be between 1000 and the server's `MAX_TIMEOUT_MS`, else `INVALID_TARGET`. */
            timeoutMs?: number;
            retry?: components["schemas"]["RetryPolicy"];
        };
        /** @description All fields optional individually, but at least one must be given. */
        JobPatch: {
            description?: string;
            tags?: string[];
            enabled?: boolean;
            schedule?: components["schemas"]["Schedule"];
            target?: components["schemas"]["Target"];
            targetKey?: string | null;
            timeoutMs?: number;
            retry?: components["schemas"]["RetryPolicy"];
        };
        Job: {
            name: components["schemas"]["JobNameValue"];
            description: string;
            tags: string[];
            enabled: boolean;
            schedule: components["schemas"]["Schedule"];
            target: components["schemas"]["Target"];
            targetKey: string | null;
            timeoutMs: number;
            retry: components["schemas"]["RetryPolicy"];
            /**
             * Format: date-time
             * @description `null` when the job is disabled or, for an `at` schedule, once it has fired.
             */
            nextRunAt: string | null;
            /**
             * Format: date-time
             * @description When the job's most recent firing was recorded (`null` before its first firing).
             */
            lastRunAt: string | null;
            /**
             * @description Terminal status of the job's most recent firing. Never `pending`/`running`/`retrying` (those are not "recorded outcomes"). `null` before the job's first firing.
             * @enum {string|null}
             */
            lastStatus: "succeeded" | "failed" | "skipped" | "cancelled" | null;
            /** @description The API key id that created the job. */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        JobList: {
            items: components["schemas"]["Job"][];
            /** @description Pass as `cursor` to fetch the next page; `null` on the last page. */
            nextCursor: string | null;
        };
        Attempt: {
            /** @description 1-based attempt number. */
            n: number;
            /** Format: date-time */
            startedAt: string;
            durationMs: number;
            /** @description `null` when the call itself failed (timeout, DNS, connection error) before a response was received. */
            httpStatus: number | null;
            error: string | null;
        };
        Run: {
            id: number;
            job: components["schemas"]["JobNameValue"];
            /** @enum {string} */
            trigger: "schedule" | "manual";
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            scheduledFor: string;
            /** @description Attempts started so far. */
            attempt: number;
            /** @description `retry.max + 1` at the time the run was created. */
            maxAttempts: number;
            /**
             * Format: date-time
             * @description Set while `pending`/`retrying`; `null` once `running` or terminal.
             */
            nextAttemptAt: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** @description Duration of the last (terminal) attempt. */
            durationMs: number | null;
            /** @description HTTP status of the last attempt. */
            httpStatus: number | null;
            /** @description First bytes of the last attempt's response body. */
            response: string | null;
            error: string | null;
            attempts: components["schemas"]["Attempt"][];
            /** Format: date-time */
            createdAt: string;
        };
        RunList: {
            items: components["schemas"]["Run"][];
            /** @description Pass as `before` to fetch the next (older) page; `null` on the last page. */
            nextBefore: string | null;
        };
        PreviewResponse: {
            /** @description The normalized cron expression. */
            cron: string;
            /** @description The resolved IANA timezone (the request's, or the server default). */
            timezone: string;
            /** @description The next upcoming firings, in order. */
            next: string[];
        };
        TargetKeysResponse: {
            /** @description Configured `TARGET_KEYS` names, sorted. */
            items: string[];
        };
        TimezonesResponse: {
            /** @description IANA timezone names supported by this Node runtime. */
            items: string[];
        };
        StatsResponse: {
            jobs: {
                total: number;
                enabled: number;
                /** @description Enabled jobs that currently have a `nextRunAt`. */
                scheduled: number;
                /**
                 * Format: date-time
                 * @description Earliest `nextRunAt` across all enabled, scheduled jobs; `null` when none.
                 */
                nextDueAt: string | null;
            };
            runs: {
                /** @description All-time counts by status. */
                byStatus: components["schemas"]["RunStatusCounts"];
                /** @description Counts by status for runs created in the trailing 24 hours. */
                last24h: components["schemas"]["RunStatusCounts"];
                /** @description Average duration of `succeeded` runs created in the trailing 24 hours; `null` when there were none. */
                avgDurationMs24h: number | null;
                /** @description Up to 10 jobs with the most `failed` runs in the trailing 24 hours, most first. */
                topFailures24h: {
                    job: string;
                    failed: number;
                }[];
            };
            worker: {
                running: boolean;
                /** @description Currently-executing calls. From the in-process `Worker` when there is one, else the durable count of `running` rows in the database. */
                inFlight: number;
                /** @description Configured `WORKER_CONCURRENCY`. */
                concurrency: number;
                /** @description Process-local counters (`succeeded`/`failed`/`retried`/`skipped`) since this process started. `null` from an API-only process, which has no in-process `Worker` and therefore no such counters — by design, not an omission. */
                sinceStart: null | {
                    succeeded: number;
                    failed: number;
                    retried: number;
                    skipped: number;
                };
            };
        };
        /** @description One count per status; all 7 keys always present (0 when there are none). */
        RunStatusCounts: {
            pending: number;
            running: number;
            retrying: number;
            succeeded: number;
            failed: number;
            skipped: number;
            cancelled: number;
        };
    };
    responses: {
        /** @description Missing or unrecognized API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "missing or invalid API key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The API key does not have the role required for this route. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "this API key has no write access"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description This service's own per-key rate limit was exceeded (distinct from any job-level HTTP outcome). */
        RateLimited: {
            headers: {
                "retry-after"?: number;
                "x-ratelimit-limit"?: number;
                "x-ratelimit-remaining"?: number;
                "x-ratelimit-reset"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "rate limit exceeded, retry in 42"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Either a body/query that fails JSON Schema validation (`VALIDATION_FAILED`) or one that passes schema validation but fails a domain rule — `INVALID_SCHEDULE`, `INVALID_TARGET` or `UNKNOWN_TARGET_KEY`. See each schema's description for exactly which rule produced which code. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The `cron` expression or `timezone` is invalid. */
        InvalidSchedule: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INVALID_SCHEDULE",
                 *         "message": "invalid cron expression: expected 5 fields, got 4"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `target.body`, JSON-encoded, exceeds `MAX_BODY_BYTES`. */
        BodyTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "BODY_TOO_LARGE",
                 *         "message": "body is 20000 bytes, limit 16384"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No job with this name exists. */
        JobNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "JOB_NOT_FOUND",
                 *         "message": "job \"nightly-export\" not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description A job with this name already exists. */
        JobExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "JOB_EXISTS",
                 *         "message": "job \"nightly-export\" already exists"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No run with this id exists. */
        RunNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RUN_NOT_FOUND",
                 *         "message": "run 42 not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The job already has a queued, running or retrying run; only one run may be in flight per job. */
        RunActive: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RUN_ACTIVE",
                 *         "message": "job \"nightly-export\" already has a queued or running run"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The run is not `pending` or `retrying` (including a `running` run, which cannot be interrupted). */
        RunNotCancellable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RUN_NOT_CANCELLABLE",
                 *         "message": "run 42 is running; only pending and retrying runs can be cancelled"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        JobName: components["schemas"]["JobNameValue"];
        RunId: string;
        /** @description Case-sensitive substring match against name and description. */
        JobsQ: string;
        /** @description Exact match against one of the job's tags. */
        JobsTag: string;
        JobsEnabled: "true" | "false";
        /** @description Opaque keyset cursor — the `name` of the last item from the previous page. */
        JobsCursor: components["schemas"]["JobNameValue"];
        /** @description Page size, 1-200. Defaults to 50. */
        Limit: string;
        RunsStatus: components["schemas"]["RunStatus"];
        RunsJob: components["schemas"]["JobNameValue"];
        /** @description Opaque keyset cursor — the `id` of the last item from the previous page. */
        RunsBefore: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "scheduler.health.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "scheduler.ready.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description The database ping failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyUnavailableResponse"];
                };
            };
        };
    };
    "scheduler.info.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance identification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    "scheduler.metrics.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text-format metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4; charset=utf-8": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    "scheduler.jobs.list": {
        parameters: {
            query?: {
                /** @description Case-sensitive substring match against name and description. */
                q?: components["parameters"]["JobsQ"];
                /** @description Exact match against one of the job's tags. */
                tag?: components["parameters"]["JobsTag"];
                enabled?: components["parameters"]["JobsEnabled"];
                /** @description Page size, 1-200. Defaults to 50. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor — the `name` of the last item from the previous page. */
                cursor?: components["parameters"]["JobsCursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.jobs.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Job created. */
            201: {
                headers: {
                    /** @description `/v1/jobs/{name}` of the created job. */
                    location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["JobExists"];
            413: components["responses"]["BodyTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.jobs.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["JobName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["JobNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.jobs.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["JobName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["JobNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.jobs.patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["JobName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPatch"];
            };
        };
        responses: {
            /** @description The updated job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["JobNotFound"];
            413: components["responses"]["BodyTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.jobs.run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["JobName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: components["schemas"]["Run"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["JobNotFound"];
            409: components["responses"]["RunActive"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.jobs.listRuns": {
        parameters: {
            query?: {
                status?: components["parameters"]["RunsStatus"];
                /** @description Page size, 1-200. Defaults to 50. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor — the `id` of the last item from the previous page. */
                before?: components["parameters"]["RunsBefore"];
            };
            header?: never;
            path: {
                name: components["parameters"]["JobName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of runs for this job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["JobNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.runs.list": {
        parameters: {
            query?: {
                job?: components["parameters"]["RunsJob"];
                status?: components["parameters"]["RunsStatus"];
                /** @description Page size, 1-200. Defaults to 50. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor — the `id` of the last item from the previous page. */
                before?: components["parameters"]["RunsBefore"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.runs.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: components["schemas"]["Run"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RunNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.runs.cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancelled run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: components["schemas"]["Run"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RunNotFound"];
            409: components["responses"]["RunNotCancellable"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.schedule.preview": {
        parameters: {
            query: {
                /** @description Five-field cron expression (or `@hourly`/`@daily`/`@weekly`/`@monthly`/`@yearly`/`@annually`/`@midnight` alias). */
                cron: string;
                /** @description IANA timezone name. Defaults to the server's `DEFAULT_TIMEZONE`. */
                timezone?: string;
                /** @description Number of upcoming firings to return, 1-50. Defaults to 5. */
                count?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized cron/timezone and the next firings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            400: components["responses"]["InvalidSchedule"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.targetKeys.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured target key names. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetKeysResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.timezones.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported timezone names. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimezonesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "scheduler.stats.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
