/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always `200 { status: "ok" }`. No dependency check, not rate-limited, not authenticated.
         */
        get: operations["search.system.health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Pings the database; the result is cached for 10 seconds. Not authenticated, not rate-limited.
         */
        get: operations["search.system.ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service identity
         * @description Static instance identity: package version, `/v1` API contract version, capability list (fixed for this service, not instance-variable), the open SQLite schema version, and the `@atc-web/service-core` version actually running. Not authenticated, not rate-limited.
         */
        get: operations["search.system.info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Prometheus text exposition format. Requires a `read`-role API key but, unlike every other authenticated route, is **not** index-scoped: a key scoped to a subset of indexes still sees per-index metric lines for every index, not only its own. Also, unlike every `/v1/*` route, it is not rate-limited and it is not under `/v1`.
         */
        get: operations["search.system.metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List visible indexes
         * @description Requires a `read`-role key. Returns only the indexes in the key's scope (or every index for an unscoped key), each with its live document count and search counter.
         */
        get: operations["search.indexes.list"];
        put?: never;
        /**
         * Create an index
         * @description Requires a `write`-role key. If the key is index-scoped, the requested `name` must be in its scope (checked after body validation, before creation) or this returns 403 — a scoped key can preemptively be issued for an index that does not exist yet.
         */
        post: operations["search.indexes.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/indexes/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        /**
         * Get one index
         * @description Requires a `read`-role key scoped to this index (or unscoped).
         */
        get: operations["search.indexes.get"];
        put?: never;
        post?: never;
        /**
         * Delete an index
         * @description Requires a `write`-role key scoped to this index (or unscoped). Deletes the index and every document in it, in one transaction.
         */
        delete: operations["search.indexes.delete"];
        options?: never;
        head?: never;
        /**
         * Update an index
         * @description Requires a `write`-role key scoped to this index (or unscoped). At least one of `description`, `weights`, `facets` is required; each given field replaces the corresponding stored value in full (`weights`/`facets` are not merged key-by-key beyond what the domain layer does internally with existing weights).
         */
        patch: operations["search.indexes.patch"];
        trace?: never;
    };
    "/v1/indexes/{name}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove every document from an index
         * @description Requires a `write`-role key scoped to this index (or unscoped). The index itself (its settings) is kept; only its documents are removed.
         */
        post: operations["search.indexes.clear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/indexes/{name}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        /**
         * Browse documents (no query)
         * @description Requires a `read`-role key scoped to this index (or unscoped). Equivalent to an empty search sorted newest-first; every returned item omits `score` entirely (it is stripped, not `null`, unlike a real search hit). Default `limit` is **50** here (search's default is 20), clamped to `maxPage` (default 100, `MAX_PAGE`). Default `offset` is 0.
         */
        get: operations["search.documents.browse"];
        /**
         * Bulk upsert documents
         * @description Requires a `write`-role key scoped to this index (or unscoped). Up to `MAX_BATCH` (default 500) documents per request, validated and indexed in one transaction: either every document lands or none do. Duplicate `id`s within the same batch are rejected.
         */
        put: operations["search.documents.upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/indexes/{name}/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
                id: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        /**
         * Get one document
         * @description Requires a `read`-role key scoped to this index (or unscoped).
         */
        get: operations["search.documents.get"];
        put?: never;
        post?: never;
        /**
         * Delete one document
         * @description Requires a `write`-role key scoped to this index (or unscoped).
         */
        delete: operations["search.documents.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/indexes/{name}/search": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        /**
         * Search (query-string form)
         * @description Requires a `read`-role key scoped to this index (or unscoped). Query form of the same search as `POST` on this path, sharing the same response shape (`SearchResult`) — but the two are intentionally **not** validated the same way:
         *     This endpoint's querystring schema is permissive: any additional query parameter is accepted as long as its value is a string of at most 2000 characters (`additionalProperties: { type: string, maxLength: 2000 }`), regardless of its name. Of those, only parameters whose name starts with the literal prefix `filter.` are actually consumed — `filter.<attrKey>=v1,v2` becomes an AND-across-keys, OR-within-key attribute filter (comma-split, one attribute key per parameter). Any other unrecognized parameter is accepted by validation and then silently ignored. This dynamic `filter.*`-prefix pattern cannot be expressed as a fixed OpenAPI parameter list; `filter.<key>` here documents the pattern, not a literal parameter named `<key>`.
         *     The `POST` form below is the strict opposite: `filters` is one explicit object field and the request body schema rejects any unknown field (`additionalProperties: false`).
         *     Default `limit` is **20** here (browse's default is 50), clamped to `maxPage` (default 100). Default `offset` is 0, `sort` is `relevance`, `highlight` is `false`.
         */
        get: operations["search.query.get"];
        put?: never;
        /**
         * Search (JSON body form)
         * @description Requires a `read`-role key scoped to this index (or unscoped). Body form of the same search as `GET` on this path, sharing the same response shape (`SearchResult`). Unlike the `GET` form, the request body schema is strict: `additionalProperties: false`, `filters` is one explicit object field (`{ "<attrKey>": ["v1", "v2"] }`, up to 20 keys, up to 50 values per key), and `highlight` is a real JSON boolean. Default `limit` is 20, clamped to `maxPage` (default 100); default `offset` is 0; default `sort` is `relevance`.
         */
        post: operations["search.query.post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/indexes/{name}/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        /**
         * Title prefix suggestions
         * @description Requires a `read`-role key scoped to this index (or unscoped). Type-ahead on titles only: folds and tokenizes `q`, matches titles whose words start with the typed words. Response items carry **only** `id` and `title` — this is not the full `DocumentView` returned by search/browse/get.
         */
        get: operations["search.suggest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate stats
         * @description Requires a `read`-role key. Not index-path-scoped (there is no `:name` parameter), but the aggregation itself only includes indexes visible to the key's own scope, unlike `GET /metrics` which reports every index regardless of scope.
         */
        get: operations["search.stats.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        IndexNameValue: string;
        Error: {
            /** @description Stable machine-readable error code, e.g. `INDEX_NOT_FOUND`. */
            code: string;
            message: string;
            /** @description Present only on some errors. An object for a domain error's extra context, or an array of `{ path, message, params }` for `VALIDATION_FAILED`. */
            details?: unknown;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /** @description 1-1000 as a plain decimal string, no leading zero. */
        LimitParam: string;
        /** @description 0 or a positive decimal string, no leading zero. */
        OffsetParam: string;
        /** @enum {string} */
        SortParam: "relevance" | "newest" | "oldest";
        /** @description Column weights for ranking; higher counts more. */
        Weights: {
            title: number;
            body: number;
            tags: number;
        };
        /** @description Partial weights; omitted fields keep their current value (create: the service default `{ title: 5, body: 1, tags: 3 }`). Each given value must be between 0 and 100. */
        WeightsInput: {
            title?: number;
            body?: number;
            tags?: number;
        };
        /** @description Attribute keys the console offers as filter groups. At most 20. */
        FacetKeys: string[];
        IndexView: {
            name: string;
            description: string;
            weights: components["schemas"]["Weights"];
            facets: string[];
            /** @description Live document count. */
            documents: number;
            /** Format: date-time */
            lastIndexedAt: string | null;
            /** @description Search requests served since process start (resets on restart, not persisted). */
            searchesSinceStart: number;
            /** @description API key id that created the index. */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        IndexResponse: {
            index: components["schemas"]["IndexView"];
        };
        IndexListResponse: {
            items: components["schemas"]["IndexView"][];
        };
        CreateIndexRequest: {
            name: components["schemas"]["IndexNameValue"];
            description?: string;
            weights?: components["schemas"]["WeightsInput"];
            facets?: components["schemas"]["FacetKeys"];
        };
        PatchIndexRequest: {
            description?: string;
            weights?: components["schemas"]["WeightsInput"];
            facets?: components["schemas"]["FacetKeys"];
        };
        ClearResult: {
            /** @description Number of documents deleted. */
            removed: number;
        };
        DocumentInput: {
            id: string;
            /** @description Required; rejected with 400 `INVALID_DOCUMENT` if empty after trimming. */
            title: string;
            body?: string;
            tags?: string[];
            /** @description Arbitrary keys (letters/digits/`_.-`, starting with a letter, ≤64 chars, not `"tags"`). Each value is a string, number, boolean, or an array of those — every scalar (array elements included) becomes a filterable/facetable value. At most `MAX_ATTRS` (default 50) values across all keys combined, or 400 `INVALID_DOCUMENT`. */
            attrs?: Record<string, never>;
            url?: string;
        };
        UpsertRequest: {
            documents: components["schemas"]["DocumentInput"][];
        };
        UpsertResult: {
            created: number;
            updated: number;
        };
        DocumentView: {
            id: string;
            title: string;
            body: string;
            tags: string[];
            attrs: Record<string, never>;
            url: string | null;
            /** @description API key id that last wrote this document. */
            source: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BrowseResponse: {
            /** @description Documents, newest first. No `score` field (stripped, not `null`). */
            items: components["schemas"]["DocumentView"][];
            total: number;
            limit: number;
            offset: number;
        };
        /** @description Present on a hit only when the request asked for `highlight=true`/`highlight: true`. */
        Highlights: {
            /** @description Original `title`, HTML-escaped, with matches wrapped in `<mark>`. */
            title: string;
            /** @description ~160-character window around the first match in `body`, `<mark>`-wrapped. */
            body: string;
        };
        SearchHit: components["schemas"]["DocumentView"] & {
            /** @description Higher is more relevant. `null` when the query had no usable search terms (a pure browse/empty query) — not present-but-zero, genuinely `null`. */
            score: number | null;
            highlights?: components["schemas"]["Highlights"];
        };
        FacetValue: {
            value: string;
            count: number;
        };
        SearchResult: {
            total: number;
            limit: number;
            offset: number;
            /** @description The parsed FTS5 match expression actually run (not the raw `q`/`filter.*` input) — empty string when the input had no usable terms. */
            query: string;
            hits: components["schemas"]["SearchHit"][];
            /** @description One entry per requested facet key, keyed by that attribute name. */
            facets: {
                [key: string]: components["schemas"]["FacetValue"][];
            };
        };
        SearchRequestBody: {
            q?: string;
            /** @description AND across keys, OR within a key. Up to 20 keys, up to 50 values per key. */
            filters?: {
                [key: string]: string[];
            };
            facets?: components["schemas"]["FacetKeys"];
            /** @description Default 20 when omitted, clamped to `maxPage` (default 100). */
            limit?: number;
            /** @description Default 0 when omitted. */
            offset?: number;
            /** @description Real JSON boolean here (the `GET` form uses a `"true"`/`"false"` string). */
            highlight?: boolean;
            sort?: components["schemas"]["SortParam"];
        };
        SuggestItem: {
            id: string;
            title: string;
        };
        SuggestResponse: {
            /** @description Title matches only — not the full `DocumentView`. */
            items: components["schemas"]["SuggestItem"][];
        };
        StatsItem: {
            name: string;
            documents: number;
            searchesSinceStart: number;
            /** Format: date-time */
            lastIndexedAt: string | null;
        };
        StatsResponse: {
            /** @description Count of visible indexes. */
            indexes: number;
            /** @description Sum of documents across visible indexes. */
            documents: number;
            /** @description Sum of searchesSinceStart across visible indexes. */
            searchesSinceStart: number;
            /** @description On-disk database size in bytes (not index-scoped — whole database file). */
            dbBytes: number;
            items: components["schemas"]["StatsItem"][];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ReadyUnavailableResponse: {
            /** @enum {string} */
            status: "unavailable";
            error: string;
        };
        InfoResponse: {
            /** @enum {string} */
            service: "search";
            /** @description This instance's package.json version. */
            version: string;
            /** @enum {string} */
            apiVersion: "v1";
            /** @description Static list for this service — bm25-ranking, facets, highlights, suggestions. */
            capabilities: string[];
            /** @description Open SQLite schema version (`PRAGMA user_version`). */
            schemaVersion: number;
            /** @description Version of `@atc-web/service-core` actually running. */
            serviceCore: string;
        };
    };
    responses: {
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `FORBIDDEN` — the API key's role does not permit this operation, or the key is scoped to a different set of indexes and this index is not in it. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `RATE_LIMITED` — more than `RATE_LIMIT_MAX` (default 1200) requests in the trailing minute for this API key. Only applies to `/v1/*` routes. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `VALIDATION_FAILED` — request fails Ajv schema validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `INDEX_NOT_FOUND`. */
        IndexNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `INDEX_EXISTS` — an index with this name already exists. */
        IndexExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IndexName: components["schemas"]["IndexNameValue"];
        DocId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "search.system.health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "search.system.ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database unreachable, or the cached check last failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyUnavailableResponse"];
                };
            };
        };
    };
    "search.system.info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    "search.system.metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics in Prometheus text format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "search.indexes.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible indexes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.indexes.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIndexRequest"];
            };
        };
        responses: {
            /** @description Index created. */
            201: {
                headers: {
                    /** @description `/v1/indexes/{name}` of the new index. */
                    location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description `INVALID_QUERY` (a weight is out of the 0-100 range, or a facet key is not a valid attribute key, or more than 20 facets) or `VALIDATION_FAILED` (request body fails schema validation, e.g. bad `name` pattern). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["IndexExists"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.indexes.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The index. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.indexes.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index (and its documents) deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.indexes.patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchIndexRequest"];
            };
        };
        responses: {
            /** @description The updated index. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description `INVALID_QUERY` (a weight out of range, or an invalid/too-many facet keys) or `VALIDATION_FAILED` (body fails schema validation, e.g. empty patch object). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.indexes.clear": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.documents.browse": {
        parameters: {
            query?: {
                /** @description Page size. Default 50, clamped to `maxPage` (default 100). */
                limit?: components["schemas"]["LimitParam"];
                /** @description Row offset. Default 0. Rejected with 400 `INVALID_QUERY` if greater than `maxOffset` (default 10000, `MAX_OFFSET`). */
                offset?: components["schemas"]["OffsetParam"];
            };
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of documents, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResponse"];
                };
            };
            /** @description `INVALID_QUERY` (`offset` greater than `maxOffset`) or `VALIDATION_FAILED` (`limit`/ `offset` fail their pattern, or an unknown query parameter is present — this endpoint's querystring schema is strict, unlike the search endpoints). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.documents.upsert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertRequest"];
            };
        };
        responses: {
            /** @description Counts of created vs. updated documents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertResult"];
                };
            };
            /** @description `INVALID_DOCUMENT` (a document fails domain validation: missing/empty `title`, disallowed `attrs` key, duplicate `id`s in the batch, ...) or `VALIDATION_FAILED` (body fails schema validation). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            /** @description `BATCH_TOO_LARGE` (more than `MAX_BATCH` documents in the request) or `DOCUMENT_TOO_LARGE` (one document's serialized size exceeds `MAX_DOC_BYTES`, default 65536 bytes). */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "search.documents.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
                id: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        document: components["schemas"]["DocumentView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description `INDEX_NOT_FOUND` or `DOCUMENT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "search.documents.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
                id: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description `INDEX_NOT_FOUND` or `DOCUMENT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "search.query.get": {
        parameters: {
            query?: {
                /** @description Search text: words are AND'd, `"phrases"` match as a unit, `-word` excludes, the last word matches as a prefix. Empty or omitted means "browse" (no ranking, `score` is `null` on every hit). */
                q?: string;
                /** @description Page size. Default 20, clamped to `maxPage` (default 100). */
                limit?: components["schemas"]["LimitParam"];
                /** @description Row offset. Default 0. Rejected with 400 `INVALID_QUERY` if greater than `maxOffset` (default 10000). */
                offset?: components["schemas"]["OffsetParam"];
                /** @description `"true"` to include `highlights` on every hit. Note: a string enum here (`"true"`/`"false"`), not a real boolean — this is the querystring form; the `POST` body form below uses a real JSON boolean for the same field. */
                highlight?: "true" | "false";
                /** @description Comma-separated attribute keys to compute facet counts for (up to 20). Each key must be a valid attribute key or `tags`, or this returns 400 `INVALID_QUERY`. */
                facets?: string;
                sort?: components["schemas"]["SortParam"];
                /** @description Dynamic pattern, not a literal parameter name — see the operation description. One occurrence per filtered attribute key, e.g. `filter.color=red,blue&filter.brand=Mavi`. */
                "filter.<key>"?: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked (or browsed) results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description `INVALID_QUERY` (offset beyond `maxOffset`, more than 32 search terms, an invalid `facets` key, or an invalid `filter.<key>` attribute key / more than 50 values for one filter key). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.query.post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SearchRequestBody"];
            };
        };
        responses: {
            /** @description Ranked (or browsed) results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description `INVALID_QUERY` (offset beyond `maxOffset`, more than 32 search terms, an invalid `facets`/`filters` attribute key) or `VALIDATION_FAILED` (body fails schema validation, e.g. an unknown field). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.suggest": {
        parameters: {
            query: {
                q: string;
                /** @description Default 10, clamped to `maxPage` (default 100). */
                limit?: components["schemas"]["LimitParam"];
            };
            header?: never;
            path: {
                name: components["parameters"]["IndexName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to `limit` title matches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["IndexNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "search.stats.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate counters across visible indexes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
