/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["auth.health.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Pings the database and verifies the mail transport. The result is cached for 30 seconds (`AuthApi.READY_CACHE_MS`).
         */
        get: operations["auth.ready.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and API contract identification */
        get: operations["auth.info.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JSON Web Key Set for access-token verification
         * @description Public verification keys for the ES256 access tokens this service signs (current key plus, during rotation, the previous key so live tokens keep verifying). Cacheable for 5 minutes.
         */
        get: operations["auth.jwks.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Authenticated (API key), but never subject to this service's own rate limiter.
         */
        get: operations["auth.metrics.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or look up users
         * @description Any valid API key may call this — there is no role gate on reads (confirmed: a `read`-only key can enumerate every user, including by exact-email lookup). Pass `email` for an exact-match lookup (returns 0 or 1 items, `nextCursor` always `null`); otherwise paginates by keyset cursor, newest first.
         */
        get: operations["auth.users.list"];
        put?: never;
        /**
         * Register a user
         * @description Requires an API key with the `write` role (`write` or `readwrite`; `read`-only keys get 403 FORBIDDEN). Registration succeeds even when the verification email fails to send — `verificationEmailSent` tells the caller whether to offer a resend.
         */
        post: operations["auth.users.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["auth.users.get"];
        put?: never;
        post?: never;
        /**
         * Delete a user
         * @description Requires an API key with the `write` role.
         */
        delete: operations["auth.users.delete"];
        options?: never;
        head?: never;
        /**
         * Update a user's name or status
         * @description Requires an API key with the `write` role. Setting `status: "disabled"` revokes every active session for the user as part of the same transaction.
         */
        patch: operations["auth.users.patch"];
        trace?: never;
    };
    "/v1/users/{id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /**
         * List a user's active sessions
         * @description Sessions that are neither revoked nor expired, as of now.
         */
        get: operations["auth.sessions.list"];
        put?: never;
        post?: never;
        /**
         * Revoke every active session for a user
         * @description Returns the count revoked. Note this endpoint returns `200` with a body, **not** `204` — unlike the single-session revoke below, the handler sends a JSON object (confirmed in source: no `reply.code(204)` on this route).
         */
        delete: operations["auth.sessions.revokeAll"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/sessions/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
                /** @description Session id. */
                sid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a single session
         * @description Idempotent create-then-delete semantics aside, a session that does not exist or does not belong to `id` returns `SESSION_NOT_FOUND` — this route does not separately check whether `id` itself refers to a real user first.
         */
        delete: operations["auth.sessions.revokeOne"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /**
         * List a user's audit events
         * @description Keyset-paginated, newest first. Note the pagination field is `nextBefore`, not `nextCursor` — this service is one of several across the platform whose list envelopes use a slightly different cursor field name (a known, not-yet-normalized cross-service inconsistency).
         */
        get: operations["auth.events.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Any valid API key may call this (no role gate — login is an end user's own action, not a back-office mutation). On success, issues a new session and returns both tokens in the body.
         */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description A refresh token that has already been rotated (replayed) revokes the whole session (`TOKEN_REUSED`) — this is a reuse-detection signal, not a benign retry.
         */
        post: operations["auth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the session owning a refresh token
         * @description Idempotent — an unknown or already-revoked refresh token still returns 204.
         */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate an access token
         * @description Never throws a domain error — an invalid, expired, or otherwise unusable token is reported in the 200 body as `active: false`, not as an HTTP error status. See `IntrospectResponse` for the exact, source-verified field combinations.
         */
        post: operations["auth.introspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume an email-verification token */
        post: operations["auth.emailVerification.verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-send the verification email
         * @description Silent (still `202`) when the email is unknown, to avoid account enumeration. A known, already-verified email returns `409 ALREADY_VERIFIED` instead — this is itself a (minor, two-way) enumeration signal, confirmed and flagged in the Phase 0 audit, not fixed here. A per-user cooldown (`RESEND_COOLDOWN_SEC`, default 60s) throttles repeat requests with `429 TOO_MANY_REQUESTS`; a separate, unrelated self-throttle (`429 RATE_LIMITED`) can also apply per API key.
         */
        post: operations["auth.emailVerification.resend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password-reset email
         * @description NOT unconditionally `202`: an unknown email or a disabled account resolves silently with `202` (no enumeration signal), and a known active account normally also gets `202` — but a request that arrives inside the per-user resend cooldown (`RESEND_COOLDOWN_SEC`, default 60s) gets `429 TOO_MANY_REQUESTS` instead, a real, source-confirmed exception to "always 202" (flagged explicitly in the Phase 0 audit — do not assume unconditional 202 for this endpoint).
         */
        post: operations["auth.password.forgot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset a password with a reset token
         * @description Revokes every session for the user and marks the email verified (proof of mailbox control) as part of the same transaction.
         */
        post: operations["auth.password.reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the current password for the calling session
         * @description Requires the end user's own access token in `X-Access-Token`, on top of the calling backend's API key in `Authorization` — checked manually in the handler via `introspect()`, not by Fastify's security machinery (there is no separate securityScheme for it). Revokes every other active session for the user; the session identified by the presented access token is kept.
         */
        post: operations["auth.password.change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: email */
        Email: string;
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable error code. */
                code: string;
                message: string;
                /** @description Present only for some errors. An object for a single domain error's structured detail (e.g. `{retryAfterSec}`, `{problems}`), or an array of `{path, message, params}` for `VALIDATION_FAILED`. `INVALID_CURSOR` never has `details` (it is a plain thrown object, not a domain `AuthError` instance). */
                details?: Record<string, never> | Record<string, never>[];
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string | null;
            /** @enum {string} */
            status: "active" | "disabled";
            emailVerified: boolean;
            /** Format: date-time */
            emailVerifiedAt: string | null;
            /**
             * Format: date-time
             * @description Null once the lockout has expired, even if the row itself has not been cleared.
             */
            lockedUntil: string | null;
            /** Format: date-time */
            passwordChangedAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Session: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string;
            /** Format: date-time */
            expiresAt: string;
            ip: string | null;
            userAgent: string | null;
        };
        Event: {
            id: number;
            /** @description e.g. login.succeeded, login.failed, session.revoked, account.disabled, password.changed. */
            type: string;
            ip: string | null;
            /** @description Parsed from the stored JSON; shape depends on `type`. */
            meta: Record<string, never> | null;
            /** Format: date-time */
            at: string;
        };
        TokenView: {
            /** @constant */
            tokenType: "Bearer";
            /** @description ES256 JWT. */
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            /** @description Opaque token. */
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            /** Format: uuid */
            sessionId: string;
        };
        AccessClaims: {
            /**
             * Format: uuid
             * @description User id.
             */
            sub: string;
            /**
             * Format: uuid
             * @description Session id.
             */
            sid: string;
            /** Format: email */
            email: string;
            email_verified: boolean;
            /** Format: uuid */
            jti: string;
            /** @description Epoch seconds. */
            iat: number;
            /** @description Epoch seconds. */
            exp: number;
            /** Format: uri */
            iss: string;
            aud: string;
        };
        UserCreateRequest: {
            email: components["schemas"]["Email"];
            /** @description Also checked against the password policy (minimum length, denylist, not the account's own email, ...). */
            password: string;
            name?: string | null;
        };
        UserPatchRequest: {
            name?: string | null;
            /** @enum {string} */
            status?: "active" | "disabled";
        };
        LoginRequest: {
            email: components["schemas"]["Email"];
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        IntrospectRequest: {
            accessToken: string;
        };
        TokenRequest: {
            token: string;
        };
        EmailOnlyRequest: {
            email: components["schemas"]["Email"];
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CreateUserResponse: {
            user: components["schemas"]["User"];
            /** @description False when the mail transport rejected the send; registration itself still succeeded. */
            verificationEmailSent: boolean;
        };
        UserResponse: {
            user: components["schemas"]["User"];
        };
        LoginResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenView"];
        };
        RevokeAllResponse: {
            /** @description Number of sessions revoked. */
            revoked: number;
        };
        AcceptedResponse: {
            /** @constant */
            accepted: true;
        };
        UserListResponse: {
            items: components["schemas"]["User"][];
            /** @description Opaque keyset cursor for the next page, or null when there is no next page. */
            nextCursor: string | null;
        };
        SessionListResponse: {
            items: components["schemas"]["Session"][];
        };
        EventListResponse: {
            items: components["schemas"]["Event"][];
            /** @description Event-id cursor for the next (older) page, or null when there is no next page. Named `nextBefore`, not `nextCursor` — this list endpoint's field name differs from `/v1/users`'s, a known cross-service/cross-endpoint inconsistency, not a typo. */
            nextBefore: string | null;
        };
        /** @description Source-verified shape of `AuthService#introspect`, exposed as-is by the HTTP handler (`{ active, ...(reason && {reason}), ...(claims && {claims}) }`). Exactly two forms occur: `active: true` always carries `claims` and never `reason`; `active: false` always carries `reason`, and additionally carries `claims` only for the two reasons where the JWT itself verified but the session or account turned out not to be usable (`SESSION_REVOKED`, `ACCOUNT_DISABLED`) — a JWT-level failure (`INVALID`, `EXPIRED`, `UNKNOWN_KEY`) never has claims to attach. */
        IntrospectResponse: {
            /** @constant */
            active: true;
            claims: components["schemas"]["AccessClaims"];
        } | {
            /** @constant */
            active: false;
            /**
             * @description INVALID/EXPIRED/UNKNOWN_KEY: the JWT itself failed verification (bad signature, expired, or signed with a key not in this service's JWKS) — `claims` absent. SESSION_REVOKED/ACCOUNT_DISABLED: the JWT verified but its session or account is no longer usable — `claims` present.
             * @enum {string}
             */
            reason: "INVALID" | "EXPIRED" | "UNKNOWN_KEY" | "SESSION_REVOKED" | "ACCOUNT_DISABLED";
            claims?: components["schemas"]["AccessClaims"];
        };
        Jwk: {
            /** @constant */
            kty: "EC";
            /** @constant */
            crv: "P-256";
            x: string;
            y: string;
            /** @description RFC 7638 JWK thumbprint. */
            kid: string;
            /** @constant */
            alg: "ES256";
            /** @constant */
            use: "sig";
        };
        JwksResponse: {
            /** @description One entry normally; two during key rotation (current + previous). */
            keys: components["schemas"]["Jwk"][];
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        ReadyResponse: {
            /** @constant */
            status: "ok";
        };
        ReadyUnavailableResponse: {
            /** @constant */
            status: "unavailable";
            error: string;
        };
        InfoResponse: {
            /** @constant */
            service: "auth";
            /** @description This service's own package.json semver. */
            version: string;
            /** @constant */
            apiVersion: "v1";
            capabilities: ("jwks" | "email-verification" | "password-reset" | "refresh-tokens")[];
            /** @description SQLite PRAGMA user_version. */
            schemaVersion: number;
            /** @description Installed @atc-web/service-core version. */
            serviceCore: string;
        };
    };
    responses: {
        /** @description UNAUTHORIZED — missing or invalid API key. */
        Unauthorized: {
            headers: {
                "www-authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "missing or invalid API key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description FORBIDDEN — the API key lacks the `write` role required for this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "this API key does not have \"write\" access"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description VALIDATION_FAILED — the request did not match its JSON Schema. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_FAILED",
                 *         "message": "body must have required property 'email'",
                 *         "details": [
                 *           {
                 *             "path": "",
                 *             "message": "must have required property 'email'",
                 *             "params": {
                 *               "missingProperty": "email"
                 *             }
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description RATE_LIMITED — this API key's own request rate exceeded `RATE_LIMIT_MAX` (default 600) per minute. Distinct from the domain `TOO_MANY_REQUESTS` cooldown on the email-resend endpoints. */
        RateLimited: {
            headers: {
                "retry-after"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "rate limit exceeded, retry in 42 seconds"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description TOO_MANY_REQUESTS — an email for this purpose was already sent within the resend cooldown (`RESEND_COOLDOWN_SEC`, default 60s). Carries `retry-after` and `details.retryAfterSec`. */
        ResendThrottled: {
            headers: {
                "retry-after"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "TOO_MANY_REQUESTS",
                 *         "message": "an email was sent recently, wait before requesting another",
                 *         "details": {
                 *           "retryAfterSec": 60
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description USER_NOT_FOUND — no user with this id. */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "USER_NOT_FOUND",
                 *         "message": "user not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description INVALID_TOKEN — the opaque token is invalid, expired, or already consumed. Exact wording varies by endpoint (e.g. "verification link is invalid or expired", "reset link is invalid or expired"). */
        InvalidToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description User id. */
        UserId: string;
        /** @description The end user's own JWT access token (not the API key). Checked manually by the handler via `introspect()`; a missing or invalid value yields `401 INVALID_TOKEN`, not a schema-level 400. */
        XAccessToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.health.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. No dependency check is performed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "auth.ready.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description A dependency check failed (cached for up to 30s). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyUnavailableResponse"];
                };
            };
        };
    };
    "auth.info.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Static service identity. `capabilities` is a fixed list for this service (no config flag makes any entry instance-variable). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    "auth.jwks.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current JWK Set. */
            200: {
                headers: {
                    "cache-control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JwksResponse"];
                };
            };
        };
    };
    "auth.metrics.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text-exposition-format metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4; charset=utf-8": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    "auth.users.list": {
        parameters: {
            query?: {
                /** @description Exact-match lookup; mutually exclusive in effect with pagination. */
                email?: components["schemas"]["Email"];
                /** @description Page size, 1-100. Default 20. */
                limit?: string;
                /** @description Opaque keyset cursor from a previous page's `nextCursor`. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description VALIDATION_FAILED (malformed query) or INVALID_CURSOR (undecodable cursor). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.users.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
            /** @description VALIDATION_FAILED (malformed body) or WEAK_PASSWORD (policy rejected). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description EMAIL_TAKEN — an account with this email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "EMAIL_TAKEN",
                     *         "message": "an account with this email already exists"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.users.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.users.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.users.patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatchRequest"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.sessions.list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.sessions.revokeAll": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — sessions revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeAllResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.sessions.revokeOne": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
                /** @description Session id. */
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked (or already revoked). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            /** @description SESSION_NOT_FOUND — no such session for this user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "SESSION_NOT_FOUND",
                     *         "message": "session not found"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.events.list": {
        parameters: {
            query?: {
                /** @description Page size, 1-100. Default 50. */
                limit?: string;
                /** @description Event id cursor from a previous page's `nextBefore`. */
                before?: string;
            };
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            /** @description UNAUTHORIZED (missing/invalid API key) or INVALID_CREDENTIALS (email or password is incorrect — the same message and status whether the email is unknown or the password is wrong, and the password hasher runs a dummy hash for an unknown email so response time does not reveal which). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description ACCOUNT_DISABLED, or EMAIL_NOT_VERIFIED (only when `LOGIN_REQUIRES_VERIFIED_EMAIL=true`, default `false`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description ACCOUNT_LOCKED — too many failed attempts (`LOGIN_MAX_FAILURES`, default 10). Carries `retry-after` and `details.retryAfterSec`. */
            423: {
                headers: {
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "ACCOUNT_LOCKED",
                     *         "message": "too many failed attempts, try again later",
                     *         "details": {
                     *           "retryAfterSec": 900
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK — a new access/refresh token pair for the same session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            /** @description UNAUTHORIZED (API key), INVALID_TOKEN (unknown, revoked, or expired refresh token), or TOKEN_REUSED (an already-rotated token was replayed; the session is revoked as a side effect). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description ACCOUNT_DISABLED — the owning account was disabled since the session was created. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "ACCOUNT_DISABLED",
                     *         "message": "account is disabled"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntrospectRequest"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntrospectResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.emailVerification.verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description OK — the user, now verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["InvalidToken"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.emailVerification.resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyRequest"];
            };
        };
        responses: {
            /** @description Accepted — either the mail was queued, or the email is unknown (both look identical to the caller by design). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            /** @description ALREADY_VERIFIED — this email belongs to an already-verified account. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "ALREADY_VERIFIED",
                     *         "message": "email is already verified"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["ResendThrottled"];
        };
    };
    "auth.password.forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyRequest"];
            };
        };
        responses: {
            /** @description Accepted, or silently a no-op for an unknown/disabled account. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["ResendThrottled"];
        };
    };
    "auth.password.reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK — the user, with a new password. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description VALIDATION_FAILED (malformed body) or WEAK_PASSWORD (policy rejected). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["InvalidToken"];
            429: components["responses"]["RateLimited"];
        };
    };
    "auth.password.change": {
        parameters: {
            query?: never;
            header: {
                /** @description The end user's own JWT access token (not the API key). Checked manually by the handler via `introspect()`; a missing or invalid value yields `401 INVALID_TOKEN`, not a schema-level 400. */
                "X-Access-Token": components["parameters"]["XAccessToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_FAILED (malformed body) or WEAK_PASSWORD (policy rejected). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description UNAUTHORIZED (missing/invalid API key), INVALID_TOKEN (`X-Access-Token` missing, malformed, expired, or its session/account no longer active), or INVALID_CREDENTIALS (`currentPassword` is wrong). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
}
