/**
 * GENERATED FILE -- do not edit by hand.
 * Produced from <repo>/openapi.yaml by `node clients/typescript/generate.mjs`.
 * Re-run generation instead of patching this file; see clients/typescript/README.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always `200`. Performs no dependency check — see `GET /ready` for that.
         */
        get: operations["media.ops.health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Runs the real dependency check (DB ping + storage layout check), cached for 30 seconds
         *     between calls (`MediaApi.READY_CACHE_MS`).
         */
        get: operations["media.ops.ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and API contract identification */
        get: operations["media.ops.info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files owned by the calling API key
         * @description Keyset pagination, newest first. `nextCursor` is an opaque, base64url-encoded
         *     `<createdAt>:<id>` token; pass it back as `cursor` to fetch the next page. `null` means no
         *     further pages.
         */
        get: operations["media.files.list"];
        /**
         * Upload a file
         * @description Raw-body upload — **not** `multipart/form-data**; no multipart dependency exists in this
         *     service. The request body is the file's bytes verbatim, piped straight into storage
         *     without buffering the whole thing in memory.
         *
         *     The real type is sniffed from the leading bytes server-side (`TypeSniffer`); any
         *     client-supplied `Content-Type` is ignored for storage/serving decisions. Raster images
         *     (`image/jpeg`, `png`, `webp`, `gif`, `avif`) are re-encoded on upload by default
         *     (`STRIP_IMAGE_METADATA=true`), which strips EXIF/GPS/XMP/ICC metadata (ICC profile is
         *     re-embedded) and defeats polyglot files; `application/pdf` and, if enabled via
         *     `ALLOWED_TYPES`, `image/svg+xml` are stored as-is.
         *
         *     Filename: the `name` query parameter wins; if absent, the `X-File-Name` header is used
         *     (URL-decoded if possible); if both are absent, a generic `file.<ext>` name is generated.
         *     Either way the name is sanitised and its extension is always re-derived from the sniffed
         *     type, never trusted from the client.
         *
         *     **Maximum upload size**: `MAX_UPLOAD_BYTES` (default 25 MiB), enforced inside the storage
         *     layer's write-stream as bytes arrive. Fastify's own `bodyLimit` config on this app
         *     (`maxUploadBytes + 1024`) is set but is dead code for this route: its enforcement only
         *     applies to parsers registered with `parseAs: 'string'|'buffer'`, and this route's raw
         *     passthrough content-type parser bypasses that check entirely. The byte cap above is real
         *     and enforced — just not by the mechanism the Fastify config implies.
         */
        put: operations["media.files.upload"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a file's metadata */
        get: operations["media.files.get"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a file
         * @description Marks the file deleted; it stops appearing in `GET /v1/files`/`GET /v1/files/{id}` and its
         *     delivery route immediately. Bytes are only physically purged after `DELETE_GRACE_DAYS`
         *     (default 7). Reversible within that window via `POST /v1/files/{id}/restore`.
         */
        delete: operations["media.files.delete"];
        options?: never;
        head?: never;
        /** Update a file's visibility and/or name */
        patch: operations["media.files.patch"];
        trace?: never;
    };
    "/v1/files/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo a soft delete
         * @description Only works within the `DELETE_GRACE_DAYS` grace window, before bytes are physically purged.
         */
        post: operations["media.files.restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/{id}/urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * (Re-)sign delivery URLs for a file
         * @description Returns a fresh `urls` map (same shape as `FileView.urls`) with a caller-chosen TTL. For a
         *     `public` file every URL is unsigned and `expiresAt` is always `null`, regardless of `ttl`.
         */
        post: operations["media.files.signUrls"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a single-use upload ticket
         * @description Lets a browser (or any caller without an API key) upload one file directly to
         *     `PUT /v1/uploads/{token}`. The ticket is consumed exactly once, on the first successful or
         *     failed upload attempt against it (a failed attempt releases it for retry); it always
         *     expires after `UPLOAD_TICKET_TTL_SEC` (default 900s) regardless of use.
         *
         *     Note: the plaintext ticket token is forwarded, unhashed, into this action's own audit
         *     event (`target.id`) — unlike every other credential in this service (API keys, and the
         *     ticket token itself in normal use), which is only ever stored or forwarded as a hash. The
         *     ticket's short lifetime and single use bound the exposure, but this is a real, confirmed
         *     inconsistency with the rest of the platform's credential-handling discipline.
         */
        post: operations["media.tickets.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload against a single-use ticket
         * @description Ticket-only auth: **no `Authorization` header is sent or checked on this route at all** —
         *     the `{token}` path segment is the sole credential, matched against the hash of a live,
         *     unused, unexpired ticket from `POST /v1/uploads`. Designed to be called directly from a
         *     browser (see the `Cors` allow-list for this route's CORS behaviour).
         *
         *     Same raw-body semantics as `PUT /v1/files` (not `multipart/form-data`) and the same
         *     server-side type sniffing, default image re-encoding/metadata stripping, and filename
         *     resolution (`name` query parameter, else `X-File-Name` header, else generated). Visibility
         *     and the upload's own byte/type limits come from the ticket itself (set when it was
         *     created), not from this request.
         *
         *     On any failure the ticket is released (not burned), so the client may retry against the
         *     same `{token}` until it expires.
         */
        put: operations["media.files.uploadTicketed"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deliver a file's original bytes or an image variant
         * @description Unauthenticated: no `Authorization` header is checked. Gating is visibility-dependent and
         *     happens inside the handler, not via any securityScheme:
         *     - `visibility: "public"` files: always served, to anyone.
         *     - `visibility: "private"` files: served only with a valid `exp`+`sig` query-string
         *       signature (HMAC-SHA256 over `fileId\nvariant\nexpiresAtSec`, minted by
         *       `POST /v1/files/{id}/urls` or a file's own `urls` field); otherwise `403 FORBIDDEN`.
         *
         *     `{variant}` is either the literal `original` or a configured preset name (default
         *     `thumb`, `small`, `medium`, `large` — see `VARIANTS`/`Config.DEFAULT_VARIANTS`; this is
         *     operator-configurable per deployment, not a fixed contract). A non-`original` variant is
         *     generated lazily on first request for a given (file, variant) pair — that first response
         *     pays image-encode latency synchronously; later requests are served from a disk cache.
         *     Variants exist only for raster images (`image/jpeg`, `png`, `webp`, `gif`, `avif`) and are
         *     always re-encoded as `image/webp` regardless of the original format; `original` always
         *     preserves the file's sniffed upload type.
         *
         *     Concurrency: generation is bounded by a process-wide semaphore
         *     (`MAX_CONCURRENT_VARIANTS`, default 4); a request that cannot get a slot within
         *     `VARIANT_WAIT_TIMEOUT_MS` (default 30s) gets `503 VARIANT_BUSY`. Concurrent requests for
         *     the *same* (file, variant) share one generation and never contend for more than one slot
         *     between them.
         *
         *     Range requests: single-range only (`Range: bytes=start-end`, `bytes=start-`, or
         *     `bytes=-suffix`). A **multi-range** `Range` header is silently treated as absent — served
         *     as a full `200`, not rejected. `If-None-Match` is honoured against a strong ETag
         *     (derived from the file's sha256 and the variant name) for conditional `304` responses.
         */
        get: operations["media.files.deliver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus text-format metrics
         * @description Authenticated like any other `/v1/*`-style route (same `Authorization: Bearer <API key>`),
         *     but registered outside `/v1` and, uniformly across this platform, exempt from this
         *     service's own rate limiter (a Prometheus scraper hits it on a fixed schedule; rate
         *     limiting it would be actively harmful).
         */
        get: operations["media.ops.metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable code, e.g. `NOT_FOUND`, `VALIDATION_FAILED`. */
                code: string;
                message: string;
                /**
                 * @description Present only for some codes: an object of domain-specific extra fields (e.g.
                 *     `{maxBytes}` on `TOO_LARGE`), or, for `VALIDATION_FAILED`, an array of
                 *     `{path, message, params}` — one entry per violated Ajv constraint.
                 */
                details?: unknown;
            };
        };
        /** Format: uuid */
        FileId: string;
        /** @enum {string} */
        Visibility: "public" | "private";
        FileName: string;
        SignedUrl: {
            /** Format: uri */
            url: string;
            /**
             * Format: date-time
             * @description `null` for a `public` file's URL (unsigned, never expires); an ISO-8601 timestamp for a `private` file's signed URL.
             */
            expiresAt: string | null;
        };
        /**
         * @description Always has `original`. Also has one entry per configured image-variant preset, but only
         *     when the file is a raster image — non-raster files (`application/pdf`, `image/svg+xml`)
         *     have `original` only. The variant preset names below (`thumb`, `small`, `medium`, `large`)
         *     are this service's *default* `VARIANTS` configuration
         *     (`Config.DEFAULT_VARIANTS`) — an operator may configure different names/sizes, so this is
         *     illustrative, not a fixed contract guarantee.
         */
        UrlsMap: {
            original: components["schemas"]["SignedUrl"];
            thumb?: components["schemas"]["SignedUrl"];
            small?: components["schemas"]["SignedUrl"];
            medium?: components["schemas"]["SignedUrl"];
            large?: components["schemas"]["SignedUrl"];
        } & {
            [key: string]: components["schemas"]["SignedUrl"];
        };
        FileView: {
            id: components["schemas"]["FileId"];
            /** @description Sanitised display name; extension always matches the sniffed type. */
            name: string;
            /** @description Server-sniffed MIME type of the `original` — never the client-supplied `Content-Type`. */
            mime: string;
            /** @description Byte size of the `original`. */
            size: number;
            /** @description Pixel width. `null` for a non-raster file (`application/pdf`, `image/svg+xml`); always set for a raster image. */
            width: number | null;
            /** @description Pixel height. `null` for a non-raster file; always set for a raster image. */
            height: number | null;
            /** @description Content hash of the `original`'s bytes (after metadata-stripping normalisation, when applied). Drives content-addressed dedup. */
            sha256: string;
            visibility: components["schemas"]["Visibility"];
            /** Format: date-time */
            createdAt: string;
            urls: components["schemas"]["UrlsMap"];
        };
        FileList: {
            items: components["schemas"]["FileView"][];
            /** @description Opaque keyset cursor for the next page, or `null` when this is the last page. */
            nextCursor: string | null;
        };
        FilePatchBody: {
            visibility?: components["schemas"]["Visibility"];
            name?: components["schemas"]["FileName"];
        };
        TicketCreateBody: {
            /** @description Defaults to `private` when omitted. */
            visibility?: components["schemas"]["Visibility"];
            /** @description Tighter cap than the service-wide `MAX_UPLOAD_BYTES`, which is the absolute ceiling regardless of this value. Defaults to `MAX_UPLOAD_BYTES` when omitted. */
            maxBytes?: number;
            /** @description Subset of this service's own `ALLOWED_TYPES`. Defaults to the full `ALLOWED_TYPES` list when omitted. */
            allowedTypes?: string[];
            /** @description Pre-set display filename for the eventual upload; overridable by the browser's own `name`/`X-File-Name` at upload time. */
            name?: components["schemas"]["FileName"];
        };
        UploadTicket: {
            /** @description Single-use credential; also the `{token}` path segment for `PUT /v1/uploads/{token}`. */
            token: string;
            /**
             * Format: uri
             * @description Fully-qualified `PUT` target, i.e. `{PUBLIC_BASE_URL}/v1/uploads/{token}`.
             */
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
            maxBytes: number;
            allowedTypes: string[];
            /** @enum {string} */
            method: "PUT";
        };
    };
    responses: {
        /** @description `UNAUTHORIZED` — missing or non-matching `Authorization: Bearer` API key. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: "Bearer";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description `TOO_LARGE` — upload exceeds `MAX_UPLOAD_BYTES` (service default 25 MiB). Enforced inside
         *     the storage layer's write-stream as bytes arrive, not by Fastify's `bodyLimit` config
         *     (which is set but inert for this raw-passthrough route).
         */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `UNSUPPORTED_TYPE` — the sniffed type (from the file's real leading bytes, never the client-supplied `Content-Type`) is unrecognised or not in `ALLOWED_TYPES`. */
        UnsupportedType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `INVALID_IMAGE` — the sniffed type is a raster image format, but the bytes fail to decode, have no dimensions, or exceed `MAX_IMAGE_PIXELS` (decompression-bomb guard). */
        InvalidImage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description `RATE_LIMITED` — this API key exceeded `RATE_LIMIT_MAX` requests/minute
         *     (service default 600) against `/v1/*`. Not applicable to `PUT /v1/uploads/{token}`,
         *     `GET /files/{id}/{variant}` or `GET /metrics`, none of which sit behind this limiter.
         */
        RateLimited: {
            headers: {
                "X-RateLimit-Limit"?: string;
                "X-RateLimit-Remaining"?: string;
                "X-RateLimit-Reset"?: string;
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        FileId: components["schemas"]["FileId"];
        /** @description Defaults to `private` when omitted. */
        UploadVisibility: components["schemas"]["Visibility"];
        /**
         * @description Display filename, 1-255 characters. Takes precedence over the `X-File-Name` header when
         *     both are given. Sanitised server-side and its extension is always re-derived from the
         *     sniffed type; a generic `file.<ext>` name is used if neither `name` nor `X-File-Name` is
         *     given.
         */
        UploadName: components["schemas"]["FileName"];
        /**
         * @description Fallback filename source, used only when the `name` query parameter is absent.
         *     URL-decoded if possible, used raw otherwise.
         */
        XFileName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "media.ops.health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    "media.ops.ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description A dependency check failed (cached result up to 30s old). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "unavailable";
                        /** @description The caught error's message. */
                        error: string;
                    };
                };
            };
        };
    };
    "media.ops.info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Static, per-instance service metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        service: "media";
                        /** @description This service's own package.json semver. */
                        version: string;
                        /** @enum {string} */
                        apiVersion: "v1";
                        /**
                         * @description Static list, always `["content-dedup", "signed-urls", "ticketed-uploads",
                         *     "soft-delete", "variants"]` for this service — no config flag makes any of
                         *     these instance-variable.
                         * @example [
                         *       "content-dedup",
                         *       "signed-urls",
                         *       "ticketed-uploads",
                         *       "soft-delete",
                         *       "variants"
                         *     ]
                         */
                        capabilities: string[];
                        /** @description SQLite `PRAGMA user_version` of the open database. */
                        schemaVersion: number;
                        /** @description Installed `@atc-web/service-core` version actually running. */
                        serviceCore: string;
                    };
                };
            };
        };
    };
    "media.files.list": {
        parameters: {
            query?: {
                /** @description Page size, 1-100. Default 20. */
                limit?: string;
                /** @description Opaque `nextCursor` value from a previous page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of files owned by the calling key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileList"];
                };
            };
            /**
             * @description `VALIDATION_FAILED` (malformed `limit`/`cursor`) or `INVALID_ARGUMENT` (`cursor`
             *     passed schema validation but does not decode to a well-formed keyset cursor).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    "media.files.upload": {
        parameters: {
            query?: {
                /** @description Defaults to `private` when omitted. */
                visibility?: components["parameters"]["UploadVisibility"];
                /**
                 * @description Display filename, 1-255 characters. Takes precedence over the `X-File-Name` header when
                 *     both are given. Sanitised server-side and its extension is always re-derived from the
                 *     sniffed type; a generic `file.<ext>` name is used if neither `name` nor `X-File-Name` is
                 *     given.
                 */
                name?: components["parameters"]["UploadName"];
            };
            header?: {
                /**
                 * @description Fallback filename source, used only when the `name` query parameter is absent.
                 *     URL-decoded if possible, used raw otherwise.
                 */
                "X-File-Name"?: components["parameters"]["XFileName"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "*/*": string;
            };
        };
        responses: {
            /** @description File stored (or deduplicated against existing identical content). */
            201: {
                headers: {
                    /** @description `/v1/files/{id}` of the stored file. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        file: components["schemas"]["FileView"];
                    };
                };
            };
            /**
             * @description `VALIDATION_FAILED` (malformed `visibility`/`name` query parameter) — or, from the
             *     upload stream itself: `EMPTY` (zero-byte body) or `STREAM_ERROR` (the request stream
             *     errored or was aborted partway through).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedType"];
            422: components["responses"]["InvalidImage"];
            429: components["responses"]["RateLimited"];
        };
    };
    "media.files.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file, scoped to the calling API key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        file: components["schemas"]["FileView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `NOT_FOUND` — file does not exist, is soft-deleted, or is owned by a different API key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "media.files.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description `NOT_FOUND` — file does not exist, is already soft-deleted, or is owned by a different API key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "media.files.patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilePatchBody"];
            };
        };
        responses: {
            /** @description The updated file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        file: components["schemas"]["FileView"];
                    };
                };
            };
            /** @description `VALIDATION_FAILED` — empty body, or a `visibility`/`name` value outside its allowed shape. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `NOT_FOUND` — file does not exist, is soft-deleted, or is owned by a different API key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "media.files.restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        file: components["schemas"]["FileView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `NOT_FOUND` — file does not exist or is owned by a different API key (restorable regardless of current soft-delete state, as long as both are true). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "media.files.signUrls": {
        parameters: {
            query?: {
                /**
                 * @description Signature lifetime in seconds. Digits only; server-side clamped to a maximum of
                 *     604800 (7 days) even if a larger value is supplied. Defaults to `SIGNED_URL_TTL_SEC`
                 *     (service default 900s) when omitted.
                 */
                ttl?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Freshly signed URLs for this file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        urls: components["schemas"]["UrlsMap"];
                    };
                };
            };
            /** @description `VALIDATION_FAILED` — malformed `ttl`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `NOT_FOUND` — file does not exist, is soft-deleted, or is owned by a different API key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    "media.tickets.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TicketCreateBody"];
            };
        };
        responses: {
            /** @description Ticket issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            /**
             * @description `VALIDATION_FAILED` (malformed body) or `INVALID_ARGUMENT` (`maxBytes` outside
             *     `1..MAX_UPLOAD_BYTES`, or `allowedTypes` includes a type this service does not itself
             *     allow via `ALLOWED_TYPES`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    "media.files.uploadTicketed": {
        parameters: {
            query?: {
                /**
                 * @description Display filename, 1-255 characters. Takes precedence over the `X-File-Name` header when
                 *     both are given. Sanitised server-side and its extension is always re-derived from the
                 *     sniffed type; a generic `file.<ext>` name is used if neither `name` nor `X-File-Name` is
                 *     given.
                 */
                name?: components["parameters"]["UploadName"];
            };
            header?: {
                /**
                 * @description Fallback filename source, used only when the `name` query parameter is absent.
                 *     URL-decoded if possible, used raw otherwise.
                 */
                "X-File-Name"?: components["parameters"]["XFileName"];
            };
            path: {
                /** @description Single-use upload ticket, exactly as returned by `POST /v1/uploads`. */
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "*/*": string;
            };
        };
        responses: {
            /** @description File stored (or deduplicated against existing identical content). */
            201: {
                headers: {
                    /** @description `/v1/files/{id}` of the stored file. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        file: components["schemas"]["FileView"];
                    };
                };
            };
            /**
             * @description `VALIDATION_FAILED` (malformed `name` query parameter) — or, from the upload stream
             *     itself: `EMPTY` (zero-byte body) or `STREAM_ERROR` (the request stream errored or was
             *     aborted partway through).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description `INVALID_TICKET` — the ticket is unknown, already used, or expired. Distinct from the API-key `UNAUTHORIZED` used elsewhere: this route never checks `Authorization`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description `TOO_LARGE` — upload exceeds the ticket's own `maxBytes` (which can be tighter than,
             *     but never looser than, the service-wide `MAX_UPLOAD_BYTES`).
             */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            415: components["responses"]["UnsupportedType"];
            422: components["responses"]["InvalidImage"];
        };
    };
    "media.files.deliver": {
        parameters: {
            query?: {
                /**
                 * @description Signature expiry, Unix seconds. Required (together with `sig`) only to read a
                 *     `private` file; ignored for a `public` file. Not a securityScheme — verified inside
                 *     the handler, not by auth middleware.
                 */
                exp?: string;
                /** @description base64url HMAC-SHA256 signature. Required (together with `exp`) only to read a `private` file; ignored for a `public` file. */
                sig?: string;
                /**
                 * @description When `1`, adds an `X-Media-Force-Download: 1` response header. Note this header is
                 *     informational only: it does **not** itself change `Content-Disposition`, which is
                 *     always derived solely from whether the delivered MIME type is an image (`inline`) or
                 *     not (`attachment`) — confirmed from source, not a design assumption.
                 */
                download?: "1";
            };
            header?: {
                /** @description Single-range only; see the operation description. */
                Range?: string;
                "If-None-Match"?: string;
            };
            path: {
                id: components["schemas"]["FileId"];
                /** @description `original`, or a configured variant preset name. */
                variant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full content. */
            200: {
                headers: {
                    ETag?: string;
                    "Accept-Ranges"?: "bytes";
                    /** @description `public, max-age=31536000, immutable` for a public file; `private, max-age=0, no-store` for a private one. */
                    "Cache-Control"?: string;
                    "Content-Type"?: string;
                    /** @description `inline` for images, `attachment` otherwise, both with an RFC 6266 filename. */
                    "Content-Disposition"?: string;
                    "Content-Security-Policy"?: "default-src 'none'; sandbox";
                    /** @description Present only when the response is not an image (non-inline). */
                    "X-Frame-Options"?: "DENY";
                    "X-Content-Type-Options"?: "nosniff";
                    "Content-Length"?: string;
                    /** @description Present only when `?download=1` was given. See the `download` parameter's description. */
                    "X-Media-Force-Download"?: "1";
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/pdf": string;
                };
            };
            /** @description Partial content for a satisfiable single-range request. */
            206: {
                headers: {
                    "Content-Range"?: string;
                    "Content-Length"?: string;
                    ETag?: string;
                    "Accept-Ranges"?: "bytes";
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/pdf": string;
                };
            };
            /** @description `If-None-Match` matched the current ETag. Same caching/type headers as `200`, empty body. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `VALIDATION_FAILED` (malformed `exp`/`sig`/`download`) or `NOT_AN_IMAGE` (a variant other than `original` was requested for a non-raster file). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description `FORBIDDEN` — the file is `private` and `exp`/`sig` are missing or do not verify. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description `NOT_FOUND` (file does not exist or is soft-deleted) or `UNKNOWN_VARIANT` (`{variant}` is not `original` and not a configured preset name). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Range request outside the resource's size, or a zero-length suffix range. */
            416: {
                headers: {
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `VARIANT_BUSY` — no generation slot became free within `VARIANT_WAIT_TIMEOUT_MS`; retry shortly. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "media.ops.metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus exposition format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4; charset=utf-8": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
